import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export type InventoryItem = {
  id: string;
  name: string;
  quantity: number;
  unit: string;
  category: string;
  notes?: string;
  status?: "good" | "maintenance" | "damaged" | "missing";
  lastCheck?: string;
  price?: number;
  serialNumber?: string;
};

export type BranchData = {
  id: string;
  name: string;
  inventory: InventoryItem[];
};

export const INVENTORY_DATA: BranchData[] = [
  {
    id: "medina",
    name: "فرع المدينة المنورة",
    inventory: [
      // BARISTA
      { id: "b-1", name: "مكينة لامرزوكو 2 جروب (La Marzocco GB5-X)", quantity: 1, unit: "حبة", category: "باريستا", status: "good", lastCheck: "2024-01-15", price: 48695.65 },
      { id: "b-2", name: "بورتا فلتر", quantity: 2, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-3", name: "ستاند اكواب", quantity: 4, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-4", name: "طاحونة اسبريسو (Mahlkonig Omnia)", quantity: 1, unit: "حبة", category: "باريستا", status: "good", lastCheck: "2024-01-15", price: 10000 },
      { id: "b-5", name: "تامبر كهربائي (Perfect Moose)", quantity: 1, unit: "حبة", category: "باريستا", status: "good", price: 869.57 },
      { id: "b-6", name: "طاحونة دريب براتزا (Baratza Forte BG)", quantity: 2, unit: "حبة", category: "باريستا", status: "good", price: 3900 },
      { id: "b-7", name: "مكينة v60 اريا 5 جروب (iRhea M5 Pro)", quantity: 1, unit: "حبة", category: "باريستا", status: "good", price: 62640 },
      { id: "b-8", name: "طاحونة Mahlkonig (E80)", quantity: 1, unit: "حبة", category: "باريستا", status: "good", price: 10450 },
      { id: "b-9", name: "سخان مياه 20 لتر (Johny Samovar)", quantity: 1, unit: "حبة", category: "باريستا", status: "good", price: 1600 },
      { id: "b-10", name: "مكينة فيتكو (Fetco)", quantity: 1, unit: "حبة", category: "باريستا", status: "good", price: 9539.13 },
      { id: "b-11", name: "حافظة قهوه 5 لتر (L4D-10)", quantity: 1, unit: "حبة", category: "باريستا", status: "good", price: 1800 },
      { id: "b-12", name: "حافظه قهوه 2.5 لتر (Airpot)", quantity: 2, unit: "حبة", category: "باريستا", status: "good", price: 460 },
      { id: "b-13", name: "حافظه قهوه 4.5", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-14", name: "مكينة برتقال فروكسول صغير", quantity: 1, unit: "حبة", category: "باريستا", status: "good", price: 5652.17 },
      { id: "b-15", name: "جهاز حساس 4 جروب لقهوة اليوم", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-16", name: "بتشر مقاس 450", quantity: 3, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-17", name: "بتشر مقاس 300", quantity: 2, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-18", name: "بتشر مقاس 600", quantity: 2, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-19", name: "صانعة ثلج ميجل", quantity: 1, unit: "حبة", category: "باريستا", status: "good", lastCheck: "2024-01-10", price: 7391.3 },
      { id: "b-20", name: "ميزان شحن", quantity: 4, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-21", name: "سيرفر مع القمع", quantity: 5, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-22", name: "كاتل كهربائي 1 لتر", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-23", name: "كاتل برتقالي 500 مل", quantity: 2, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-24", name: "ثالجه 2 باب ستيل", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-25", name: "شيكر مقاس 750", quantity: 4, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-26", name: "خالط كهربائي للمشروبات", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-27", name: "كوب اسبريسو سراميك", quantity: 10, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-28", name: "صحن خشبي لالسبريسو", quantity: 6, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-29", name: "باسكت للبن", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-30", name: "طابعة كاشير", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "b-31", name: "محطة قهوة مع ترامس (Koz Tree + Thermos)", quantity: 1, unit: "مجموعة", category: "باريستا", status: "good", price: 30000, notes: "عدد 2 كوز تري + 4 ترامس 5 لتر" },

      { id: "b-32", name: "طفريات خشب (48 حبة)", quantity: 48, unit: "حبة", category: "باريستا", status: "good", price: 72 },

      // CASHIER
      { id: "c-1", name: "ايباد مع الشاحن", quantity: 1, unit: "حبة", category: "كاشير", status: "good" },
      { id: "c-2", name: "جهاز بيجر مع الشاحن", quantity: 7, unit: "حبة", category: "كاشير", status: "good" },
      { id: "c-3", name: "صرافتين مع الشاحن", quantity: 1, unit: "حبة", category: "كاشير", status: "good" },
      { id: "c-4", name: "ايباد المنيو", quantity: 1, unit: "حبة", category: "كاشير", status: "good" },
      { id: "c-5", name: "طابعة كاشير", quantity: 2, unit: "حبة", category: "كاشير", status: "good" },
      { id: "c-6", name: "مكينة صوت", quantity: 1, unit: "حبة", category: "كاشير", status: "good" },
      { id: "c-7", name: "توصيله كهرباء", quantity: 1, unit: "حبة", category: "كاشير", status: "good" },
      { id: "c-8", name: "جهاز هنقرستيشن مع الشاحن", quantity: 1, unit: "حبة", category: "كاشير", status: "good" },
      { id: "c-9", name: "جهاز تو يو مع الشاحن", quantity: 1, unit: "حبة", category: "كاشير", status: "good" },
      { id: "c-10", name: "طابعه ورق hp", quantity: 1, unit: "حبة", category: "كاشير", status: "good" },
      { id: "c-11", name: "درج كاشير للنقدية", quantity: 1, unit: "حبة", category: "كاشير", status: "good" },

      // KITCHEN
      { id: "k-1", name: "موقد كهربائي 4 اعين (حديد زهر)", quantity: 1, unit: "حبة", category: "المطبخ", status: "good", price: 3137.62 },
      { id: "k-2", name: "قالية زيت بالكهرباء", quantity: 2, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "k-3", name: "صاج شواء بسطح املس 61سم", quantity: 1, unit: "حبة", category: "المطبخ", status: "good", price: 3029.4 },
      { id: "k-4", name: "ثالجة اندر كاونتر 4 باب", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "k-5", name: "ثالجة اندر كاونتر 2 باب", quantity: 1, unit: "حبة", category: "المطبخ", status: "good", price: 3900 },
      { id: "k-6", name: "فريزر 2 باب", quantity: 2, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "k-7", name: "شوك فريزر (Mastercool Blast Chiller 5 Trays)", quantity: 1, unit: "حبة", category: "المطبخ", status: "good", price: 12000 },
      { id: "k-8", name: "عجان (Mecnosud 60kg)", quantity: 1, unit: "حبة", category: "المطبخ", status: "good", price: 16000 },
      { id: "k-9", name: "ميكسر (Mecnosud Planetary Mixer 40 Lt)", quantity: 1, unit: "حبة", category: "المطبخ", status: "good", price: 19000 },
      { id: "k-10", name: "فرادة عجين (Mecnosud Manual Dough Sheeter)", quantity: 1, unit: "حبة", category: "المطبخ", status: "good", price: 13914 },
      { id: "k-11", name: "عجان صغير", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "k-12", name: "مسدس لهب TOTAL", quantity: 2, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "k-13", name: "ترولى", quantity: 2, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "k-14", name: "راك استيل", quantity: 36, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "k-15", name: "راك بالستيك أبيض كبير", quantity: 55, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "k-16", name: "راك بالستيك ابيض صغير", quantity: 5, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "k-17", name: "طابعة كاشير", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "k-18", name: "مضرب كهربائي", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "k-19", name: "شواية سلامندر (Salamander)", quantity: 1, unit: "حبة", category: "المطبخ", status: "good", price: 1906.89 },
      { id: "k-20", name: "قطاعة لحوم (Slicer)", quantity: 1, unit: "حبة", category: "المطبخ", status: "good", price: 1430.17 },
      { id: "k-21", name: "فرن هجين (Giorik PoP Speed Steam Hybrid)", quantity: 1, unit: "حبة", category: "المطبخ", status: "good", price: 11000 },
      { id: "k-22", name: "فرن كونفكشن (Unox Convection Oven 10 Trays)", quantity: 2, unit: "حبة", category: "المطبخ", status: "good", price: 15800 },
      { id: "k-23", name: "خمارة عجين (Unox BakerLux Proofer)", quantity: 2, unit: "حبة", category: "المطبخ", status: "good", price: 5500 },
      { id: "k-24", name: "غسالة صحون (Dish Washer GS 50 ECO)", quantity: 1, unit: "حبة", category: "المطبخ", status: "good", price: 7000 },

      // PIZZA
      { id: "p-1", name: "ثالجة اندر كاونتر 2 باب (بانكول)", quantity: 1, unit: "حبة", category: "بيتزا", status: "good", price: 3500 },
      { id: "p-2", name: "فرن بيتزا (فولاذ يعمل بالغاز)", quantity: 1, unit: "حبة", category: "بيتزا", status: "good", price: 17136.02 },
      { id: "p-3", name: "مكنسة فرن", quantity: 1, unit: "حبة", category: "بيتزا", status: "good" },
      { id: "p-4", name: "بيل التقاط بيتزا", quantity: 2, unit: "حبة", category: "بيتزا", status: "good", price: 65.22 },
      { id: "p-5", name: "طابعة كاشير", quantity: 1, unit: "حبة", category: "بيتزا", status: "good" },

      // GENERAL / FURNITURE
      { id: "g-1", name: "كرسي شبك", quantity: 54, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-2", name: "طاولة دائرية", quantity: 19, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-3", name: "كرسي خشب", quantity: 12, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-4", name: "كرسي خشب صغير", quantity: 5, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-5", name: "طاولة خشب", quantity: 2, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-6", name: "طاولة دائريى رخام", quantity: 3, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-7", name: "طاولة مربعة رخام", quantity: 3, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-8", name: "كرسي جلد", quantity: 9, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-9", name: "جلسات ساكو", quantity: 12, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-10", name: "دفاية غاز", quantity: 5, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-11", name: "صندوق بلدية", quantity: 6, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-12", name: "مظلة BB", quantity: 4, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-13", name: "شاشة 32 بوصة", quantity: 4, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-14", name: "شاشة 98 بوصة", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-15", name: "ستارة هواء", quantity: 4, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-16", name: "تكييف", quantity: 4, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-17", name: "جريالت سوداء", quantity: 19, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-18", name: "سماعات", quantity: 6, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-19", name: "راوتر انترنت", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-20", name: "كاميرات مراقبة 360 درجة", quantity: 3, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-21", name: "كاميرات مراقبة", quantity: 14, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-22", name: "وحدة تحكم بالكاميرات", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-23", name: "جهاز تسجيل الكاميرات", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-24", name: "صندوق أجهزة الكاميرات", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-25", name: "صندوق شاشة + شاتر", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-26", name: "طفاية حريق", quantity: 4, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-27", name: "لوجو بتر بيكرى", quantity: 5, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-28", name: "فخاريات", quantity: 15, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-29", name: "صائد حشرات", quantity: 4, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-30", name: "دينامو مضخة مياه", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-31", name: "غطاس", quantity: 2, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-32", name: "خزان مياه", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-33", name: "عوامة", quantity: 2, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-34", name: "سخان مياه كهرباء", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-35", name: "غرفة تبريد", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-36", name: "باب خزان ارضى", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-37", name: "أسطوانة غاز", quantity: 5, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-38", name: "طقم مفكات", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-39", name: "باب خشب", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-40", name: "باب دفاع مدنى", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-41", name: "ستارة قماش مطبوع bb", quantity: 20, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-42", name: "شفاط دخان", quantity: 2, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-43", name: "ماكينة غرفة التبريد", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-44", name: "وحدات تكييف خارجية", quantity: 4, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-45", name: "قطع ضخ مياه النافورة", quantity: 3, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-46", name: "كشاف النافورة", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-47", name: "كشاف طوارئ", quantity: 4, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-48", name: "كشاف زرع", quantity: 45, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-49", name: "صندوق خشب بتر بيكرى", quantity: 6, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-50", name: "ثالجة عرض 1.5م (بانكول شوكولاته)", quantity: 2, unit: "حبة", category: "أثاث وعام", status: "good", price: 8250 },
      { id: "g-51", name: "ثالجة عرض 1.2 م (بانكول)", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good", price: 7400 },
      { id: "g-52", name: "رف ستيل معلق", quantity: 9, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-53", name: "طاولة ستيل", quantity: 5, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "g-54", name: "رف ستيل ارضي", quantity: 3, unit: "حبة", category: "أثاث وعام", status: "good" },
    ]

  },
  {
    id: "tabuk",
    name: "فرع تبوك",
    inventory: [
      { id: "t-1", name: "الكمرات", quantity: 16, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-2", name: "السماعات", quantity: 7, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-3", name: "المظلات", quantity: 6, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-4", name: "حوض زرع", quantity: 37, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-5", name: "دفايا مربعة", quantity: 6, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-6", name: "دفاية غاز طويلة", quantity: 5, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-7", name: "نافورة موية صغيرة", quantity: 6, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-8", name: "كرسي حديد مجدول", quantity: 53, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-9", name: "طاولة دائرية طويلة", quantity: 14, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-10", name: "طاولة دائرية قصيرة", quantity: 8, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-11", name: "نافورة كبيرة", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-12", name: "لوحة بتر بيكري", quantity: 2, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-13", name: "لوحة المدخل صغيرة وكبيرة", quantity: 2, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-14", name: "كاونتر خدمة", quantity: 2, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-15", name: "ثلاجة تبريد 2 باب", quantity: 5, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-16", name: "فرن يونكس مع الخمارة", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-17", name: "فرن يونكس مع الخمارة", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-18", name: "ترولي", quantity: 3, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-19", name: "فرن بيتزا غاز", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-20", name: "ثلاجة كاونتر تبريد دريسنج 3 باب", quantity: 2, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-21", name: "ثلاجة كاونتر تبريد 2 باب", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-22", name: "ثلاجة فريزر 1 باب", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-23", name: "ثلاجة كاونتر تبريد 4 باب", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-24", name: "ماكينة غسيل", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-25", name: "سلمندر", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-26", name: "حامل بهارات", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-27", name: "ثلاجة فريزر كبيرة", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-28", name: "عجانة 60 لتر", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-29", name: "مكسر حلويات كبير", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-30", name: "رف حائط", quantity: 4, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-31", name: "فرادة عجين", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-32", name: "طاولة استيل 3 رف", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-33", name: "طاولة استيل 1 رف", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-34", name: "حافظة طحين كبيرة", quantity: 4, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-35", name: "حافظة طحين صغيرة", quantity: 6, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-36", name: "حامل استيل كبير 4 رف", quantity: 2, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-37", name: "حامل استيل صغير 4 رف", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-38", name: "ماكينة قهوة لامرزوكا استراد", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-39", name: "طاحونة اسبريسو", quantity: 2, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-40", name: "تمير اسبريسو", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-41", name: "حامل اكواب", quantity: 2, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-42", name: "موازين v60", quantity: 5, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-43", name: "سيرفر v60", quantity: 4, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-44", name: "طاحونة قهوة مقطرة", quantity: 2, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-45", name: "ماكينة برتقال", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-46", name: "ايس ميكر كبير وصغير", quantity: 2, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-47", name: "فلتر كامل مع الخزان", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-48", name: "باسكت", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-49", name: "ثلاجة عرض 3 باب", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-50", name: "رينزر", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-51", name: "ماكينة قهوة اليوم (فيتكو)", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-52", name: "حافظة مشروبات ساخنة", quantity: 2, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-53", name: "ماكينة هوت شوكليت", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-54", name: "خلاط استيل", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-55", name: "جريل", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-56", name: "فرن بوتجاز 4 عين", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-57", name: "سلايزر", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-58", name: "خلاط عادي", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-59", name: "ثلاجة عرض صغيرة", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-60", name: "ثلاجة عرض طويلة", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      
      // NEW ITEMS FROM PDF (December 09, 2025)
      { id: "t-61", name: "فريزر تبريد (مستودع)", quantity: 1, unit: "حبة", category: "المطبخ", status: "good", notes: "المستودع" },
      { id: "t-62", name: "مكيف هواء سبليت", quantity: 8, unit: "حبة", category: "أثاث وعام", status: "good", notes: "سكن عمال" },
      { id: "t-63", name: "شاشة مراقبة الكاميرات", quantity: 2, unit: "حبة", category: "أثاث وعام", status: "good", notes: "1 في الكاميرات، 1 في مكان آخر (بند 8 وبند 3)" },
      { id: "t-64", name: "أسطوانة غاز", quantity: 10, unit: "حبة", category: "المطبخ", status: "good", notes: "7 مستودع دفايا + 3 سكن عمال" },
      { id: "t-65", name: "جهاز كمبيوتر", quantity: 1, unit: "حبة", category: "كاشير", status: "good" },
      { id: "t-66", name: "طابعة", quantity: 1, unit: "حبة", category: "كاشير", status: "good" },
      { id: "t-67", name: "طفاية حريق", quantity: 5, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-68", name: "عربة بلدية", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-69", name: "ماكينة آيس كريم", quantity: 1, unit: "حبة", category: "باريستا", status: "good" },
      { id: "t-70", name: "حامل شاشة", quantity: 2, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-71", name: "صائدة حشرات", quantity: 6, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-72", name: "حامل شاشة 96 بوصة", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-73", name: "جهاز بي إن سبورت", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-74", name: "شاشة عرض منتجات", quantity: 2, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-75", name: "مكيف", quantity: 3, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-76", name: "شاشة 96 بوصة", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-61", name: "سلم 2 درج", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-62", name: "حوض غسيل استيل", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-63", name: "طاولة استيل 4 رف", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-64", name: "ستائر هواء", quantity: 2, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-65", name: "مكسر حلويات", quantity: 2, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-66", name: "فرن تسخين مايكرويف", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-67", name: "اير برش", quantity: 1, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-68", name: "ميزان", quantity: 2, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-69", name: "مكبس كريمات وصوصات", quantity: 2, unit: "حبة", category: "المطبخ", status: "good" },
      { id: "t-70", name: "طاولة خدمة بيضاء", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-71", name: "كرسي جلد", quantity: 14, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-72", name: "كرسي داخلي خشب", quantity: 13, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-73", name: "كرسي خشب منجد صغير", quantity: 12, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-74", name: "طاولة دائرية خشب داخلية", quantity: 3, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-75", name: "طاولة خشب دائرية مربعة", quantity: 4, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-76", name: "طاولة خشب دائرية صغيرة", quantity: 4, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-77", name: "مرآة كبيرة مع لوجو", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-78", name: "طاولة شيرينج طويلة", quantity: 1, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-79", name: "كنب جلد داخلي", quantity: 4, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-80", name: "فخار كبير", quantity: 2, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-81", name: "فخار وسط", quantity: 3, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-82", name: "فخار صغير", quantity: 10, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-83", name: "فخار صغير XS", quantity: 7, unit: "حبة", category: "أثاث وعام", status: "good" },
      { id: "t-84", name: "كنب جلسة 2 حبة", quantity: 16, unit: "حبة", category: "أثاث وعام", status: "good" },
    ]
  }
];
