-- =====================================================
-- بيانات المؤثرين - للاستيراد في Supabase
-- تاريخ: 2026-01-10
-- عدد السجلات: 83 مؤثر
-- =====================================================

-- ملاحظة: تأكد من وجود جدول marketing_influencers قبل تنفيذ هذه الأوامر
-- قم بتنفيذ ملف supabase_marketing_influencers_update.sql أولاً إذا لزم الأمر

INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('كشاف الرياض', 'كشاف الرياض', '', '506336350', 'food', ARRAY['tiktok']::TEXT[], 133000, '133k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@iaz.199?_r=1&_t=ZS-92qDxAOdjGv', 'https://vt.tiktok.com/ZSPT7SwBr/', 60, 'SA8405000068200549497000', 'علي عبدالقادر عثمان', 'الانماء', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('تغطيات عمر', 'تغطيات عمر', '', '', 'food', ARRAY['tiktok']::TEXT[], 296000, '296k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@omar.ss2?_r=1&_t=ZS-92qE8mzdFPo', 'https://vt.tiktok.com/ZSPT7kaKV/', 80, 'SA78 8000 0114 6080 1600 2100', 'عمر علي السبر', 'الراجحي', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('ثامر', 'ثامر', '', '553455808', 'food', ARRAY['tiktok']::TEXT[], 121000, '121k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@thamer.86?_r=1&_t=ZS-92qHCYXGT3M', 'https://vt.tiktok.com/ZSPT7jvx1/', 80, 'SA6110000026052577000109', 'ثامر محمد مباركي', 'الأهلي', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('نورينا', 'نورينا', '', '', 'food', ARRAY['tiktok']::TEXT[], 245000, '245k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@norina20014?_r=1&_t=ZS-92qIr3Tf0Zo', 'https://vt.tiktok.com/ZSPT7FY4s/', 30, 'SA4480000501608010314197', 'نوره فلاح القحطاني', 'الراجحي', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('ريم', 'ريم', '', '', 'food', ARRAY['tiktok']::TEXT[], 54000, '54k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@memeabdull?_r=1&_t=ZS-92qLUaDGM3p', 'https://vt.tiktok.com/ZSPT7RkE1/', 30, 'SA51 1000 0011 1001 9872 2008', 'REEM ABDULLAH NASSER ALOQAYLI', 'لاهلي', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('تغطيات لمو', 'تغطيات لمو', '', '', 'food', ARRAY['tiktok']::TEXT[], 99000, '99k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@lamamakeup5?_r=1&_t=ZS-92qLktctku4', 'https://vt.tiktok.com/ZS5mULQHT/', 30, 'SA2705000068202309150000', 'لمى سليمان الشميمري', 'الانماء', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('إبراهيم سعود', 'إبراهيم سعود', '', '580296146', 'food', ARRAY['tiktok']::TEXT[], 249000, '249k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@e5bll?_r=1&_t=ZS-92qMAs6udCn', 'https://vt.tiktok.com/ZS5dmrA8X/', 80, 'SA9180000219608010009097', 'ابراهيم سعود العبدالله', 'الراجحي', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('riyadhcrv', 'riyadhcrv', '', '533419716', 'food', ARRAY['tiktok']::TEXT[], 99000, '99k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@riyadhcrv?_r=1&_t=ZS-92qRLVsjsYe', 'https://vt.tiktok.com/ZS5m91snK/', 80, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('تجرب هديل', 'تجرب هديل', '', '', 'food', ARRAY['tiktok']::TEXT[], 6000, '6k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@hadeel.review?_r=1&_t=ZS-92qRYNyWOqy', 'https://vt.tiktok.com/ZS5m9hU55/', 80, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('nony blog', 'nony blog', '', '', 'food', ARRAY['tiktok']::TEXT[], 50000, '50k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@j.bloggg?_r=1&_t=ZS-92qT5p9lzm9', 'https://vt.tiktok.com/ZS5mCByWj/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('wajan blogger', 'wajan blogger', '', '', 'food', ARRAY['tiktok']::TEXT[], 22000, '22k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@rivo81?_r=1&_t=ZS-92qTh5rNb5I', 'https://vt.tiktok.com/ZS5mCGEq7/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('BDBD', 'BDBD', '', '', 'food', ARRAY['tiktok']::TEXT[], 1000, '1k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@baz.78?_r=1&_t=ZS-92qUmZUcmGa', 'https://vt.tiktok.com/ZS5m4hR95/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('deem.alrajhi', 'deem.alrajhi', '', '', 'food', ARRAY['tiktok']::TEXT[], 18000, '18k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@deem.alrajhi?_r=1&_t=ZS-92qV5cHxa9V', 'https://vt.tiktok.com/ZS5mVJ3hc/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('wadha blogger', 'wadha blogger', '', '', 'food', ARRAY['tiktok']::TEXT[], 646, '646f', 'الرياض', 'الرياض', 'https://www.tiktok.com/@wadhainriyadh?_r=1&_t=ZS-92qVlHz6fZt', 'https://vt.tiktok.com/ZS5mqDTug/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('سماهر', 'سماهر', '', '', 'food', ARRAY['tiktok']::TEXT[], 66000, '66k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@essfais?_r=1&_t=ZS-92rqQXePNZc', 'https://vt.tiktok.com/ZS5Hp1DSX/', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('غدير', 'غدير', '', '', 'food', ARRAY['tiktok']::TEXT[], 19000, '19k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@nlefr1?_r=1&_t=ZS-92rsSjcurob', 'https://vt.tiktok.com/ZS5HtTu8u/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('by lama', 'by lama', '', '', 'food', ARRAY['tiktok']::TEXT[], 5, '5f', 'الرياض', 'الرياض', 'https://www.tiktok.com/@lama.trends?_r=1&_t=ZS-92rzw1otW1E', 'https://vt.tiktok.com/ZS591Pfj1/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('غادة المطيري', 'غادة المطيري', '', '', 'food', ARRAY['tiktok']::TEXT[], 24000, '24k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@gh_almo?_r=1&_t=ZS-92s04jLoXtV', 'https://vt.tiktok.com/ZS591Waxp/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('لين منصور', 'لين منصور', '', '', 'food', ARRAY['tiktok']::TEXT[], 17000, '17k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@leen_26o6?_r=1&_t=ZS-92s0K1eWOUH', 'https://vt.tiktok.com/ZS59J9bVu/', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('ra', 'ra', '', '', 'food', ARRAY['tiktok']::TEXT[], 17000, '17k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@xiarm_x?_r=1&_t=ZS-92s0apI8zyP', 'https://vt.tiktok.com/ZS59eRgwW/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('memeabdull', 'memeabdull', '', '', 'food', ARRAY['tiktok']::TEXT[], 54000, '54k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@memeabdull?_r=1&_t=ZS-92s0o6O2CiD', 'https://vt.tiktok.com/ZS59JKrT4/', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('bee', 'bee', '', '', 'food', ARRAY['tiktok']::TEXT[], 133000, '133k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@fooodie.bee?_r=1&_t=ZS-92s0zgkqAJI', 'https://vt.tiktok.com/ZS59e6gET/', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('fluffy', 'fluffy', '', '', 'food', ARRAY['tiktok']::TEXT[], 6000, '6k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@mela_fluffy22?_r=1&_t=ZS-92s1FhlL8z6', 'https://vt.tiktok.com/ZS59enFEE/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('يلا نجرب سوا', 'يلا نجرب سوا', '', '', 'food', ARRAY['tiktok']::TEXT[], 42000, '42k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@nourhblogger?_r=1&_t=ZS-92s1YdFL2NJ', 'https://vt.tiktok.com/ZS59d9DcE/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('مزايا الرياض', 'مزايا الرياض', '', '', 'food', ARRAY['tiktok']::TEXT[], 10000, '10k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@mazaya_alriyadh?_r=1&_t=ZS-92s1fmRiGeL', 'https://vt.tiktok.com/ZS59d6ADr/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('توصيات روري', 'توصيات روري', '', '', 'food', ARRAY['tiktok']::TEXT[], 8000, '8k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@ryosmj?_r=1&_t=ZS-92s1pp6LN0X', 'https://vt.tiktok.com/ZS59d3wj1/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('تغطيات احمد', 'تغطيات احمد', '', '561261262', 'food', ARRAY['tiktok']::TEXT[], 104000, '104k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@ahmedecr?_r=1&_t=ZS-92s2nqdxHpU', 'https://vt.tiktok.com/ZS598CFrN/', 80, 'SA8605000068201342335000', 'احمد خلف ملفي ال دخنان', 'الانماء', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('تجارب ايمن', 'تجارب ايمن', '', '', 'food', ARRAY['tiktok']::TEXT[], 1000, '1k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@ae_m40?_r=1&_t=ZS-92s35YYhMhA', 'https://vt.tiktok.com/ZS598H5Qt/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('بلوقر ميمي', 'بلوقر ميمي', '', '', 'food', ARRAY['tiktok']::TEXT[], 10000, '10k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@mymy20h?_r=1&_t=ZS-92s3MLBa4Ky', 'https://vt.tiktok.com/ZS59LQ8Wt/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('rawabi', 'rawabi', '', '', 'food', ARRAY['tiktok']::TEXT[], 37000, '37k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@rawabij22?_r=1&_t=ZS-92s3Ulr4FMq', 'https://vt.tiktok.com/ZS59LaUJo/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('عدسة التجارب', 'عدسة التجارب', '', '', 'food', ARRAY['tiktok']::TEXT[], 31000, '31k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@lens.exp?_r=1&_t=ZS-92s3bfgEkIn', 'https://vt.tiktok.com/ZS59LPt2M/', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('ميم', 'ميم', '', '', 'food', ARRAY['tiktok']::TEXT[], 3000, '3k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@i_mesh95?_r=1&_t=ZS-92s3j1reRKX', 'https://vt.tiktok.com/ZS59LTNba/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('lifelong', 'lifelong', '', '', 'food', ARRAY['tiktok']::TEXT[], 22000, '22k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@lifelong_99?_r=1&_t=ZS-92s3oyQcvob', 'https://vt.tiktok.com/ZS59LEkD8/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('blogger lara', 'blogger lara', '', '', 'food', ARRAY['tiktok']::TEXT[], 3000, '3k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@lssww?_r=1&_t=ZS-92s41BM03BV', 'https://vt.tiktok.com/ZS59NB9Kf/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('فهد', 'فهد', '', '', 'food', ARRAY['tiktok']::TEXT[], 1000, '1k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@l2tl0?_r=1&_t=ZS-92s483jokpZ', 'https://vt.tiktok.com/ZS59Nm9qw/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('صبا', 'صبا', '', '', 'food', ARRAY['tiktok']::TEXT[], 16000, '16k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@8spri?_r=1&_t=ZS-92s4E7v8fAK', 'https://vt.tiktok.com/ZS59N3gEM/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('haya hamad', 'haya hamad', '', '', 'food', ARRAY['tiktok']::TEXT[], 5000, '5k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@iammhayya?_r=1&_t=ZS-92s4KptiF8u', 'https://vt.tiktok.com/ZS59Nqf74/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('beyond nada', 'beyond nada', '', '531985431', 'food', ARRAY['tiktok']::TEXT[], 12000, '12k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@beyondksa8?_r=1&_t=ZS-92s4T6GCkPk', 'https://vt.tiktok.com/ZS59NnFVJ/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('المصورة مها', 'المصورة مها', '', '', 'food', ARRAY['tiktok']::TEXT[], 14000, '14k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@mhaaljibryn?_r=1&_t=ZS-92s4hK95GoG', 'https://vt.tiktok.com/ZS59FFEUQ/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('raghad', 'raghad', '', '', 'food', ARRAY['tiktok']::TEXT[], 24000, '24k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@raghd120?_r=1&_t=ZS-92s5A4pf4dg', 'https://vt.tiktok.com/ZS59YrAvk/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('bitesbsos', 'bitesbsos', '', '', 'food', ARRAY['tiktok']::TEXT[], 777, '777f', 'الرياض', 'الرياض', 'https://www.tiktok.com/@bitesbysos?_r=1&_t=ZS-92s5GxlEOTF', 'https://vt.tiktok.com/ZS59Ykkyq/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('dana blogger', 'dana blogger', '', '533057625', 'food', ARRAY['tiktok']::TEXT[], 101000, '101k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@ya.daily0?_r=1&_t=ZS-92s5MtLnUJQ', 'https://vt.tiktok.com/ZS59YQPBC/', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('hind', 'hind', '', '', 'food', ARRAY['tiktok']::TEXT[], 10000, '10k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@hind82hh?_r=1&_t=ZS-92s5WxUH8EP', 'https://vt.tiktok.com/ZS59YnkKE/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('A', 'A', '', '', 'food', ARRAY['tiktok']::TEXT[], 1000, '1k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@athub08?_r=1&_t=ZS-92s5dzKVO3I', 'https://vt.tiktok.com/ZS592NHMe/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('اريج فايبز', 'اريج فايبز', '', '', 'food', ARRAY['tiktok']::TEXT[], 14000, '14k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@areej_vibes?_r=1&_t=ZS-92s89KwreJY', 'https://vt.tiktok.com/ZS59rexWM/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('قمر all riyadh', 'قمر all riyadh', '', '', 'food', ARRAY['tiktok']::TEXT[], 1000, '1k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@all.riyadh?_r=1&_t=ZS-92s8IebhfrY', 'https://vt.tiktok.com/ZS59rMTtx/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('بيان', 'بيان', '', '', 'food', ARRAY['tiktok']::TEXT[], 7000, '7k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@sa_773333?_r=1&_t=ZS-92s8nrIERHw', 'https://vt.tiktok.com/ZS59hAwmC/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('تجارب', 'تجارب', '', '', 'food', ARRAY['tiktok']::TEXT[], 19000, '19k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@hello_itsme_2030?_r=1&_t=ZS-92teWsMNlpM', 'https://vt.tiktok.com/ZS5QxeyAP/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('reem', 'reem', '', '556836003', 'food', ARRAY['tiktok']::TEXT[], 116000, '116k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@vuyeq?_r=1&_t=ZS-92tebodYyuq', 'https://vt.tiktok.com/ZS5QxrQry/', 80, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('ashwag blogger', 'ashwag blogger', '', '', 'food', ARRAY['tiktok']::TEXT[], 105000, '105k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@ass.saudi?_r=1&_t=ZS-92tej2yOdMb', 'https://vt.tiktok.com/ZS5QxY8bH/', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('سديم', 'سديم', '', '', 'food', ARRAY['tiktok']::TEXT[], 34000, '34k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@sadeem_b25?_r=1&_t=ZS-92trwlOTHXR', 'https://vt.tiktok.com/ZS5QK6aEo/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('تغطيات جوري', 'تغطيات جوري', '', '554859422', 'food', ARRAY['tiktok']::TEXT[], 88000, '88k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@joury.riyadh?_r=1&_t=ZS-92tjIt6mcpY', 'https://vt.tiktok.com/ZS5QbQfuF/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('شروق', 'شروق', '', '', 'food', ARRAY['tiktok']::TEXT[], 61000, '61k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@bloggersh2?_r=1&_t=ZS-92tjnms7wgP', 'https://vt.tiktok.com/ZS5Qguskw/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('هيا تغطيات الرياض', 'هيا تغطيات الرياض', '', '', 'food', ARRAY['tiktok']::TEXT[], 106000, '106k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@haya_sn?_r=1&_t=ZS-92tjqzmOTZ6', 'https://vt.tiktok.com/ZS5QgaM94/', 80, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('شهد الزهراني', 'شهد الزهراني', '', '556189755', 'food', ARRAY['tiktok']::TEXT[], 169000, '169k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@liliiq18?_r=1&_t=ZS-92tjtaZKzqv', 'https://vt.tiktok.com/ZS5Qg9aNU/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('ريو', 'ريو', '', '532388816', 'food', ARRAY['tiktok']::TEXT[], 206000, '206k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@moz.9?_r=1&_t=ZS-92tjwlD4mMm', 'https://vt.tiktok.com/ZS5QgXwk2/', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('ياسر خطة الرياض', 'ياسر خطة الرياض', '', '', 'food', ARRAY['tiktok']::TEXT[], 69000, '69k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@yass.alq?_r=1&_t=ZS-92tkJ5TcPOW', 'https://vt.tiktok.com/ZS5QpJsFc/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('رسيل', 'رسيل', '', '', 'food', ARRAY['tiktok']::TEXT[], 59000, '59k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@rasel_reviews?_r=1&_t=ZS-92tpdXpjRBM', 'https://vt.tiktok.com/ZS5QcMdwv/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('خبايا الرياض', 'خبايا الرياض', '', '595885405', 'food', ARRAY['tiktok']::TEXT[], 113000, '113k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@riyadh_coverage1?_r=1&_t=ZS-92tps3AuBtM', 'https://vt.tiktok.com/ZS5QcqJKQ/', 80, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('onthego', 'onthego', '', '', 'food', ARRAY['tiktok']::TEXT[], 1000, '1k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@itsmh86?_r=1&_t=ZS-92tqubEpDgC', 'https://vt.tiktok.com/ZS5QTS99Y/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('شوق سلمان', 'شوق سلمان', '', '', 'food', ARRAY['tiktok']::TEXT[], 9000, '9k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@.vvcnr?_r=1&_t=ZS-92tr0NenVKe', 'https://vt.tiktok.com/ZS5QTGhDS/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('نوف', 'نوف', '', '553217666', 'food', ARRAY['tiktok']::TEXT[], 65000, '65k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@nouf.sr?_r=1&_t=ZS-92tr3TYBjnQ', 'https://vt.tiktok.com/ZS5QTSRxE/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('تغطيات نوره س', 'تغطيات نوره س', '', '', 'food', ARRAY['tiktok']::TEXT[], 35000, '35k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@i12nn?_r=1&_t=ZS-92trEvLckQG', 'https://vt.tiktok.com/ZS5QwJ1MA/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('مشاري المطيري', 'مشاري المطيري', '', '555695305', 'food', ARRAY['tiktok']::TEXT[], 244000, '244k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@mesharifahadms?_r=1&_t=ZS-92trK2eIOQv', 'https://vt.tiktok.com/ZS5QTcuYd/', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('dahm', 'dahm', '', '508855458', 'food', ARRAY['tiktok']::TEXT[], 131000, '131k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@ixii43_?_r=1&_t=ZS-92trQI2nS5N', 'https://vt.tiktok.com/ZS5QwL36V/', 80, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('بلوقر جوجو', 'بلوقر جوجو', '', '', 'food', ARRAY['tiktok']::TEXT[], 12000, '12k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@7_ja_?_r=1&_t=ZS-92trYhX2IPU', 'https://vt.tiktok.com/ZS5QwkXcu/', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('تغطياتDL', 'تغطياتDL', '', '', 'food', ARRAY['tiktok']::TEXT[], 2000, '2k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@just.triyng?_r=1&_t=ZS-92trZK4Xay4', 'https://vt.tiktok.com/ZS5Qwr58m/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('هنا رياضنا', 'هنا رياضنا', '', '553465019', 'food', ARRAY['tiktok']::TEXT[], 91000, '91k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@riyadhblog2022?_r=1&_t=ZS-92tre5CYAgm', 'https://vt.tiktok.com/ZS5Qwkh2a/', 30, 'SA30 8000 0470 6080 1027 5841', 'ايمان احمد عبدالله الهنيدي', 'الراجحي', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('تغطيات و أماكن الرياض eh', 'تغطيات و أماكن الرياض eh', '', '', 'food', ARRAY['tiktok']::TEXT[], 68000, '68k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@emo.elegant?_r=1&_t=ZS-92tridd74PU', 'https://vt.tiktok.com/ZS5QKRwM3/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('رغد', 'رغد', '', '', 'food', ARRAY['tiktok']::TEXT[], 24000, '24k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@raghd120?_r=1&_t=ZS-92ts7c7rkRB', 'https://vt.tiktok.com/ZS5QKYEJb/', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('يارا الرياض', 'يارا الرياض', '', '597448122', 'food', ARRAY['tiktok']::TEXT[], 19000, '19k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@your__71?_r=1&_t=ZS-92twE4dfUpQ', '', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('دليل السعودية', 'دليل السعودية', '', '538842687', 'food', ARRAY['tiktok']::TEXT[], 219000, '219k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@l_na_333?_r=1&_t=ZS-92twHmT6SW5', '', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('فعاليات الرياض', 'فعاليات الرياض', '', '551491992', 'food', ARRAY['tiktok']::TEXT[], 367000, '367k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@riyadh_evnt?_r=1&_t=ZS-92twAJMG4rl', '', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('الزين', 'الزين', '', '', 'food', ARRAY['tiktok']::TEXT[], 100000, '100k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@zeen_50x?_r=1&_t=ZS-92twL2uDaA1', '', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('ندي الشافعي', 'ندي الشافعي', '', '559533476', 'food', ARRAY['tiktok']::TEXT[], 95000, '95k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@nadaalsahafi?_r=1&_t=ZS-92twQtiPjeP', '', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('beautiful riyadh', 'beautiful riyadh', '', '595174466', 'food', ARRAY['tiktok']::TEXT[], 25000, '25k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@beautiful_riyadh1?_r=1&_t=ZS-92twYVlLOFg', '', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('retaj', 'retaj', '', '534217457', 'food', ARRAY['tiktok']::TEXT[], 108000, '108k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@r9lia?_r=1&_t=ZS-92twfZba101', '', 80, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('تدى ال جميل', 'تدى ال جميل', '', '566538926', 'food', ARRAY['tiktok']::TEXT[], 99000, '99k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@nada_aljamel?_r=1&_t=ZS-92twoVit2tJ', '', 80, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('مشعل الحربي', 'مشعل الحربي', '', '501174032', 'food', ARRAY['tiktok']::TEXT[], 66000, '66k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@meshal_harb?_r=1&_t=ZS-92twyQCAyzk', '', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('trendy riyadh vip', 'trendy riyadh vip', '', '553600657', 'food', ARRAY['tiktok']::TEXT[], 55000, '55k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@trendyriyadh1?_r=1&_t=ZS-92txHKtMLqf', '', 50, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('evan', 'evan', '', '', 'food', ARRAY['tiktok']::TEXT[], 214000, '214k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@793y?_r=1&_t=ZS-92txMtXlFLB', '', 30, '', '', '', TRUE, NOW(), NOW());
INSERT INTO marketing_influencers (name, name_ar, email, phone, specialty, platforms, follower_count, follower_count_text, city, region, account_url, coverage_url, view_rating, bank_account_number, bank_account_holder, bank_name, is_active, created_at, updated_at) VALUES ('مريم العبدلي', 'مريم العبدلي', '', '539660113', 'food', ARRAY['tiktok']::TEXT[], 132000, '132k', 'الرياض', 'الرياض', 'https://www.tiktok.com/@md.iii80?_r=1&_t=ZS-92txPtKGHkD', '', 50, '', '', '', TRUE, NOW(), NOW());

-- تم إنشاء الملف بنجاح
