import { readFileSync } from "node:fs";
import ts from "typescript";
import { describe, expect, it, vi } from "vitest";
import { operationsNoticeScopeAllowed } from "../shared/notification-recipient";
import { recognizedSourceNotice } from "../shared/operations-center-notifications";

const src = ts.createSourceFile("server/push-service.ts", readFileSync("server/push-service.ts", "utf8"), ts.ScriptTarget.Latest, true);
let original: ts.FunctionDeclaration | undefined;
function visit(node: ts.Node) {
  if (ts.isFunctionDeclaration(node) && node.name?.text === "filterOperationsNotificationScope") original = node;
  ts.forEachChild(node, visit);
}
visit(src);
if (!original) throw new Error("Missing Push recipient scope filter");
const fn = original.getText(src).replace('await import("./source-notification-projection")', "deps");
const compiled = ts.transpileModule(fn, { compilerOptions: { target: ts.ScriptTarget.ES2022 } }).outputText;
type Projector = (notice: any, userId: string) => Promise<any>;
function filter(projector: Projector) {
  const db: any = {
    select: (fields: any) => ({ from: (table: string) => ({ where: async () =>
      table === "users" ? [{ id: "ops", role: "operations_manager" }] : [{ uid: "ops", branchId: "a" }],
    }) }),
  };
  return new Function("db", "users", "userBranchAccess", "inArray",
    "operationsNoticeScopeAllowed", "recognizedSourceNotice", "deps",
    `${compiled}; return filterOperationsNotificationScope;`)(
    db, "users", "grants", () => "WHERE", operationsNoticeScopeAllowed, recognizedSourceNotice,
    { projectSourceNotificationForRecipient: projector }) as
    (notice: any, candidateIds: string[]) => Promise<string[]>;
}

describe("Push recipient branch authorization from live source projection", () => {
  const manual = { targetAllBranches: false, targetBranchIds: ["a", "b"], accessBranchIds: ["a", "b"] };
  const source = { ...manual, autoGenerated: true, autoSource: "reverse_movement" };
  it("rejects partial multi-branch manual scope even for an exact user", async () => {
    const projector = vi.fn(async (n: any) => n);
    expect(await filter(projector)(manual, ["ops"])).toEqual([]);
    expect(projector).not.toHaveBeenCalled();
  });
  it("reprojects workflow recipient before comparing the branch and rejects revoked source access", async () => {
    const projector = vi.fn(async (n: any) =>
      ({ ...n, targetAllBranches: false, targetBranchIds: ["a"], accessBranchIds: ["a"] }));
    expect(await filter(projector)(source, ["ops"])).toEqual(["ops"]);
    expect(projector).toHaveBeenCalledWith(source, "ops");
    projector.mockImplementationOnce(async () => null);
    expect(await filter(projector)(source, ["ops"])).toEqual([]);
    projector.mockImplementationOnce(async (n: any) =>
      ({ ...n, targetAllBranches: false, targetBranchIds: ["b"], accessBranchIds: ["b"] }));
    expect(await filter(projector)(source, ["ops"])).toEqual([]);
  });
});