import { beforeEach, describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { noticeInSelectedScope, recognizedSourceNotice } from "../shared/operations-center-notifications";

const state = vi.hoisted(() => ({
  role: "operations_manager", branchIds: ["b"] as string[], active: true,
  modules: ["warehouse", "central_kitchen_orders", "production"] as string[],
  recipients: ["recipient"] as string[], reads: [] as string[],
  transfer: { id: 42, sourceBranchId: "a", destinationBranchId: "b", status: "in_transit", hasDiscrepancy: false },
  kitchen: { id: 9, centralKitchenId: "a", requestBranchId: "b", status: "dispatched", discrepancyStatus: "none" },
  assignment: { id: "7", source_type: "material_transfer", source_id: 42, driver_id: "driver", status: "awaiting_receipt",
    event_type: "awaiting_receipt", revision: "event:18", event_id: "18", detail: null },
}));
vi.mock("../server/db", () => ({
  db: { select: () => ({ from: () => ({ where: async () => [state.transfer] }) }) },
  pool: { query: vi.fn(async (sql: string, values: any[]) => {
    state.reads.push(sql);
    if (sql.includes("delivery_notification_outbox")) return { rows: [state.assignment] };
    if (sql.includes("material_transfers")) return { rows: [{ source: "a", destination: "b", status: state.transfer.status }] };
    if (sql.includes("is_active='active'")) return { rows: (Array.isArray(values[0]) ? values[0] : [values[0]]).map(id => ({ id })) };
    throw new Error(`Unexpected source query: ${sql}`);
  }) },
}));
vi.mock("../server/source-notification-access", () => ({
  sourceNoticeAccess: async () => state.active ? {
    user: { id: "recipient", role: state.role, jobTitle: "manager", branchId: "b" },
    allowed: state.branchIds,
    branch: (id: string) => state.branchIds.includes(id),
    view: async (module: string) => state.modules.includes(module),
  } : null,
}));
vi.mock("../server/warehouse-transfer-notifications", () => ({
  filterAuthorizedWarehouseTransferNotificationUsers: async (_db: unknown, _n: unknown, ids: string[]) =>
    ids.filter(id => state.recipients.includes(id)),
  routedWarehouseTransferRecipients: async () => state.recipients,
}));
vi.mock("../server/central-kitchen-notifications", () => ({
  filterAuthorizedCentralKitchenNotificationUsers: async (_db: unknown, _n: unknown, ids: string[]) =>
    ids.filter(id => state.recipients.includes(id)),
  centralKitchenNoticeContext: async () => ({ order: state.kitchen, event: "dispatched" }),
}));
import { projectSourceNotificationForRecipient, kitchenNoticeIsCurrent, transferNoticeIsCurrent } from "../server/source-notification-projection";
import { deliveryNoticeDestination, deliveryNoticeIsCurrent } from "../server/delivery-notifications";

function notice(overrides: Record<string, unknown> = {}) {
  return { id: 10, autoGenerated: true, autoSource: "warehouse_material_transfer", accessModule: "warehouse",
    targetUserIds: ["recipient"], targetAllBranches: false, targetBranchIds: ["b"], accessBranchIds: ["a", "b"],
    dedupeKey: "warehouse-transfer:42:in_transit:in_transit", title: "تحويل في الطريق",
    content: "أرسل المصدر التحويل إلى الفرع المستلم.", buttonText: "فتح التحويل",
    buttonAction: "/transfer-requests?branchId=b&transferId=42", ...overrides } as any;
}
const access = (role: string, branches: string[] | null, modules: string[]) => ({
  user: { id: "recipient", role, branchId: "b", jobTitle: "manager" }, allowed: branches,
  branch: (id: string) => !!id && (branches === null || branches.includes(id)),
  view: async (module: string) => modules.includes(module),
}) as any;

beforeEach(() => {
  state.role = "operations_manager"; state.branchIds = ["b"]; state.active = true;
  state.modules = ["warehouse", "central_kitchen_orders", "production"]; state.recipients = ["recipient"];
  state.transfer.status = "in_transit"; state.transfer.hasDiscrepancy = false;
  state.kitchen.status = "dispatched"; state.reads = [];
  state.assignment.event_type = "awaiting_receipt"; state.assignment.status = "awaiting_receipt";
});

describe("source-authorized selected-side projection", () => {
  it("allows a B-only recipient scope without disclosing unselected side A", async () => {
    const original = notice();
    expect(noticeInSelectedScope(original, ["b"])).toBeNull();
    const projected = await projectSourceNotificationForRecipient(original, "recipient");
    expect(projected).toMatchObject({ accessBranchIds: ["b"], targetBranchIds: ["b"],
      buttonAction: "/transfer-requests?branchId=b&transferId=42", dedupeKey: original.dedupeKey });
    expect(noticeInSelectedScope(projected!, ["b"])).toEqual({ kind: "branch", branchIds: ["b"] });
    expect(noticeInSelectedScope(projected!, ["a"])).toBeNull();
    expect(original.accessBranchIds).toEqual(["a", "b"]);
  });
  it("uses source side for source follow-up; does not infer destination authority", async () => {
    state.branchIds = ["a"]; state.transfer.status = "pending";
    const projected = await projectSourceNotificationForRecipient(notice({ dedupeKey: "warehouse-transfer:42:created:created" }), "recipient");
    expect(projected).toMatchObject({ accessBranchIds: ["a"], buttonAction: "/transfer-requests?branchId=a&transferId=42" });
    state.branchIds = ["b"];
    expect(await projectSourceNotificationForRecipient(notice({ dedupeKey: "warehouse-transfer:42:created:created" }), "recipient")).toBeNull();
  });
  it("keeps manual/arbitrary multibranch text fail closed; recognition alone is not authorization", async () => {
    for (const overrides of [{ autoGenerated: false }, { autoSource: "manual" }, { dedupeKey: "manual:42" }]) {
      const original = notice(overrides);
      expect(recognizedSourceNotice(original)).toBeNull();
      expect(await projectSourceNotificationForRecipient(original, "recipient")).toBe(original);
      expect(noticeInSelectedScope(original, ["b"])).toBeNull();
    }
    state.recipients = [];
    expect(await projectSourceNotificationForRecipient(notice(), "recipient")).toBeNull();
    expect(await projectSourceNotificationForRecipient(notice(), "forged-user")).toBeNull();
  });
  it("revokes immediately on current source custody, branch or account loss", async () => {
    expect(await projectSourceNotificationForRecipient(notice(), "recipient")).not.toBeNull();
    state.branchIds = [];
    expect(await projectSourceNotificationForRecipient(notice(), "recipient")).toBeNull();
    state.branchIds = ["b"]; state.active = false;
    expect(await projectSourceNotificationForRecipient(notice(), "recipient")).toBeNull();
    state.active = true; state.recipients = [];
    expect(await projectSourceNotificationForRecipient(notice(), "recipient")).toBeNull();
  });
  it("permission loss removes the CTA without inventing another grant", async () => {
    state.modules = [];
    expect(await projectSourceNotificationForRecipient(notice(), "recipient")).toMatchObject({
      buttonAction: null, buttonText: null, accessBranchIds: ["b"],
    });
  });
  it("a later stage is factual history, not an obsolete receipt action", async () => {
    state.transfer.status = "delivered";
    const projected = await projectSourceNotificationForRecipient(notice(), "recipient");
    expect(projected).toMatchObject({ sourceState: "history", buttonAction: null, buttonText: null });
    expect(projected?.content).not.toContain("يحتاج");
    expect(projected?.content).toContain("سُجّل");
    expect(transferNoticeIsCurrent("created", { status: "approved" })).toBe(false);
    expect(kitchenNoticeIsCurrent("dispatched", { status: "received" })).toBe(false);
    expect(kitchenNoticeIsCurrent("received_discrepancy", { status: "received", discrepancyStatus: "resolved" })).toBe(false);
    expect(deliveryNoticeIsCurrent({ status: "receipt_approved" }, "awaiting_receipt")).toBe(false);
    const scheduled_at = new Date(Date.now() + 60_000);
    expect(deliveryNoticeIsCurrent({ status: "assigned", scheduled_at, driver_id: "driver",
      revision: `deadline:${Math.floor(scheduled_at.getTime() / 1000)}:driver` }, "overdue")).toBe(false);
  });
  it("projects existing kitchen records to the current recipient side", async () => {
    const kitchen = notice({ autoSource: "central_kitchen_order", accessModule: "central_kitchen_orders",
      dedupeKey: "central-kitchen-event:18:dispatched", buttonAction: "/central-kitchen-orders?branchId=b&orderId=9" });
    expect(await projectSourceNotificationForRecipient(kitchen, "recipient")).toMatchObject({
      accessBranchIds: ["b"], buttonAction: "/central-kitchen-orders?branchId=b&orderId=9",
    });
    state.role = "production_development_manager"; state.branchIds = ["a"];
    expect(await projectSourceNotificationForRecipient(kitchen, "recipient")).toMatchObject({
      accessBranchIds: ["a"], buttonAction: "/central-kitchen-orders?branchId=a&orderId=9",
    });
  });
  it("projects an existing delivery row read-only; repeated reads do not enqueue or send", async () => {
    const delivery = notice({ autoSource: "delivery_task", accessModule: "delivery_tasks", dedupeKey: "delivery:18:recipient",
      accessBranchIds: ["b"], buttonAction: "/driver-deliveries?deliveryId=7" });
    for (let i = 0; i < 2; i++) {
      expect(await projectSourceNotificationForRecipient(delivery, "recipient")).toMatchObject({
        buttonAction: "/transfer-requests?branchId=b&transferId=42&deliveryId=7", dedupeKey: delivery.dedupeKey,
      });
    }
    expect(state.reads.length).toBeGreaterThan(0);
    expect(state.reads.every(sql => /^\s*SELECT\b/i.test(sql))).toBe(true);
    const projector = readFileSync("server/source-notification-projection.ts", "utf8");
    expect(projector).not.toMatch(/enqueueDeliveryNotice|sendPush|\.insert\(|INSERT INTO/);
    const sender = readFileSync("server/delivery-notifications.ts", "utf8");
    expect(sender).toContain("ON CONFLICT (dedupe_key) DO NOTHING");
    expect(sender).toContain("ON CONFLICT (assignment_id,event_type,revision) DO NOTHING");
  });
});

describe("recipient-specific delivery source destinations", () => {
  const assignment = { id: "7", source_type: "material_transfer", source_id: 42, driver_id: "recipient",
    status: "awaiting_receipt", scheduled_at: null, created_by: "actor" } as any;
  it.each(["operations_manager", "production_development_manager"])("never sends %s to the standalone desk", async role => {
    expect(await deliveryNoticeDestination(assignment, { source: "a", destination: "b" }, "awaiting_receipt",
      access(role, ["b"], ["warehouse", "delivery_tasks"]))).toEqual({
      href: "/transfer-requests?branchId=b&transferId=42&deliveryId=7", branchId: "b",
    });
  });
  it("keeps authorized current drivers on their existing exact driver selection", async () => {
    const driver = access("employee", ["b"], ["delivery_tasks"]);
    driver.user.jobTitle = "delivery";
    expect(await deliveryNoticeDestination(assignment, { source: "a", destination: "b" }, "awaiting_receipt", driver))
      .toEqual({ href: "/driver-deliveries?deliveryId=7", branchId: "b" });
    expect(await deliveryNoticeDestination({ ...assignment, source_type: "reverse_movement" },
      { source: null, destination: null, sourceWarehouseId: 1, destinationWarehouseId: 2, kind: "warehouse_transfer" },
      "assigned", driver)).toEqual({ href: "/driver-deliveries?deliveryId=7", branchId: null });
    driver.user.id = "another";
    expect(await deliveryNoticeDestination(assignment, { source: "a", destination: "b" }, "awaiting_receipt", driver)).toBeNull();
  });
  it.each([
    ["kitchen", { source: "a", destination: "b" }, "awaiting_receipt", ["b"], ["central_kitchen_orders"], "/central-kitchen-orders?branchId=b&orderId=42&deliveryId=7"],
    ["reverse_movement", { source: "a", destination: "b", kind: "material_return" }, "awaiting_receipt", ["b"], ["warehouse"], "/reverse-logistics?branchId=b&movementId=42&deliveryId=7"],
    ["finished_goods_transfer", { source: "a", destination: "b" }, "awaiting_receipt", ["b"], ["production"], "/finished-goods-inventory?branchId=b&transferId=42&deliveryId=7"],
    ["kitchen_warehouse_shipment", { source: "a", destination: null, warehouseId: 1 }, "failed", ["a"], ["production"], "/kitchen-warehouse-shipping?branchId=a&kitchenId=a&shipmentId=42&deliveryId=7"],
  ] as const)("uses exact canonical source endpoint for %s", async (type, source, event, branches, modules, href) => {
    expect(await deliveryNoticeDestination({ ...assignment, source_type: type }, source, event,
      access("production_development_manager", [...branches], [...modules]))).toEqual({
      href, branchId: branches[0],
    });
  });
  it("stays linkless for revoked resources, unavailable route permissions or managed-warehouse custody", async () => {
    expect(await deliveryNoticeDestination(assignment, { source: "a", destination: "b" }, "awaiting_receipt",
      access("operations_manager", ["a"], ["warehouse"]))).toBeNull();
    expect(await deliveryNoticeDestination(assignment, { source: "a", destination: "b" }, "awaiting_receipt",
      access("operations_manager", ["b"], ["delivery_tasks"]))).toBeNull();
    expect(await deliveryNoticeDestination({ ...assignment, source_type: "reverse_movement" },
      { source: "a", destination: "b", kind: "warehouse_transfer" }, "awaiting_receipt",
      access("operations_manager", ["b"], ["warehouse"]))).toBeNull();
    expect(await deliveryNoticeDestination({ ...assignment, source_type: "finished_goods_transfer" },
      { source: "a", destination: "b" }, "failed", access("production_development_manager", ["a"], ["production"]))).toBeNull();
  });
});