import { and, eq, inArray, or, sql } from "drizzle-orm";
import { getKitchenRouting, routingPeople, routingPermission } from "./central-kitchen-routing";
import {
  systemNotifications,
  centralKitchenOrders,
  centralKitchenOrderEvents,
  userBranchAccess,
  userPermissions,
  users,
  type SystemNotification,
} from "@shared/schema";
import { loadCentralKitchenOrderingPolicy } from "./central-kitchen-ordering-policy";

export type CentralKitchenNotificationEvent =
  | "created"
  | "edited"
  | "cancelled"
  | "approved"
  | "prepared"
  | "dispatched"
  | "received"
  | "received_discrepancy"
  | "missing_responsible"
  | "overdue"
  | "discrepancy_resolved";

const EVENT_COPY: Record<CentralKitchenNotificationEvent, { title: string; content: string; priority: number }> = {
  missing_responsible: { title: "طلب دون مسؤول مطبخ", content: "يرجى تعيين مسؤول أو نائب مؤهل للمطبخ.", priority: 4 },
  overdue: { title: "طلب مطبخ متأخر", content: "تجاوز الطلب موعد الاحتياج ولم يتم استلامه.", priority: 4 },
  created: { title: "طلب جديد للمطبخ المركزي", content: "وصل طلب فرع جديد ويحتاج إلى المراجعة.", priority: 3 },
  edited: { title: "تم تعديل طلب المطبخ المركزي", content: "عدّل الفرع الطالب بيانات طلب قائم.", priority: 2 },
  cancelled: { title: "تم إلغاء طلب المطبخ المركزي", content: "ألغى الفرع الطالب طلباً قائماً.", priority: 3 },
  approved: { title: "تم اعتماد طلب المطبخ المركزي", content: "اعتمد المطبخ المركزي الطلب.", priority: 2 },
  prepared: { title: "تم تجهيز طلب المطبخ المركزي", content: "أكمل المطبخ المركزي تجهيز الطلب.", priority: 2 },
  dispatched: { title: "تم إرسال طلب المطبخ المركزي", content: "خرج الطلب من المطبخ المركزي للتسليم.", priority: 3 },
  received: { title: "تم استلام طلب المطبخ المركزي", content: "أكد الفرع الطالب استلام الطلب.", priority: 2 },
  received_discrepancy: { title: "تم استلام الطلب مع فروقات", content: "سجّل الفرع الطالب فروقات عند استلام الطلب وتحتاج إلى المراجعة.", priority: 4 },
  discrepancy_resolved: { title: "تمت معالجة فروقات طلب المطبخ", content: "تم إغلاق فروقات الاستلام المسجلة على الطلب.", priority: 3 },
};

export function canReceiveCentralKitchenNotification(
  role: string,
  permissionActions: string[] | null,
): boolean {
  return role === "admin"
    || role === "production_development_manager"
    || role === "branch_manager"
    || !!permissionActions?.includes("view");
}

export function buildCentralKitchenNotificationPayload(input: {
  eventId: number;
  orderId: number;
  event: CentralKitchenNotificationEvent;
  branchId: string;
  actorId: string;
  recipientIds: string[];
}) {
  const copy = EVENT_COPY[input.event];
  return {
    title: copy.title,
    content: copy.content,
    messageType: "central_kitchen_order",
    displayStyle: "banner",
    priority: copy.priority,
    targetAllBranches: false,
    targetBranchIds: [input.branchId],
    targetUserIds: input.recipientIds,
    buttonText: "فتح الطلب",
    buttonAction: `/central-kitchen-orders?branchId=${encodeURIComponent(input.branchId)}&orderId=${input.orderId}`,
    soundEnabled: true,
    // NotificationDisplay marks the row read as soon as it is rendered.
    // showOnce prevents the same lifecycle banner/sound replaying on reload,
    // while the normal read record remains available to notification history.
    showOnce: true,
    autoGenerated: true,
    autoSource: "central_kitchen_order",
    accessModule: "central_kitchen_orders",
    accessBranchIds: [input.branchId],
    dedupeKey: `central-kitchen-event:${input.eventId}:${input.event}`,
    createdBy: input.actorId,
  } as const;
}

type DatabaseExecutor = {
  select: (...args: any[]) => any;
  insert: (...args: any[]) => any;
};

export async function resolveCentralKitchenNotificationRecipients(
  executor: DatabaseExecutor,
  branchIds: string[],
  candidateUserIds?: string[],
): Promise<string[]> {
  if (!branchIds.length || candidateUserIds?.length === 0) return [];
  const branchUsers = executor.select({ userId: userBranchAccess.userId })
    .from(userBranchAccess)
    .where(inArray(userBranchAccess.branchId, branchIds));
  const rows = await executor.select({
    id: users.id,
    role: users.role,
    permissionActions: userPermissions.actions,
  }).from(users)
    .leftJoin(userPermissions, and(
      eq(userPermissions.userId, users.id),
      eq(userPermissions.module, "central_kitchen_orders"),
    ))
    .where(and(
      eq(users.isActive, "active"),
      or(
        ...(candidateUserIds ? [eq(users.role, "admin"), eq(users.role, "operations_manager"), eq(users.role, "production_development_manager")] : []),
        inArray(users.branchId, branchIds),
        inArray(users.id, branchUsers),
      ),
      ...(candidateUserIds ? [inArray(users.id, candidateUserIds)] : []),
    ));

  return Array.from(new Set(rows
    .filter((row: any) => canReceiveCentralKitchenNotification(
      row.role,
      Array.isArray(row.permissionActions) ? row.permissionActions : null,
    ))
    .map((row: any) => row.id)));
}

export async function filterAuthorizedCentralKitchenNotificationUsers(
  executor: DatabaseExecutor,
  notification: Pick<SystemNotification, "accessModule" | "accessBranchIds"> & Partial<SystemNotification>,
  candidateUserIds: string[],
): Promise<string[]> {
  if (notification.accessModule !== "central_kitchen_orders") return candidateUserIds;
  let event = notification.dedupeKey?.split(":").at(-1) as CentralKitchenNotificationEvent;
  const orderId = Number(notification.buttonAction?.match(/orderId=(\d+)/)?.[1]);
  if (orderId && !EVENT_COPY[event]) {
    const eventId = Number(notification.dedupeKey?.match(/^central-kitchen-event:(\d+)$/)?.[1]);
    if (eventId) {
      const [row] = await executor.select().from(centralKitchenOrderEvents)
        .where(and(eq(centralKitchenOrderEvents.id, eventId), eq(centralKitchenOrderEvents.orderId, orderId)));
      event = row?.eventType as CentralKitchenNotificationEvent;
    }
  }
  if (orderId && EVENT_COPY[event]) {
    const [order] = await executor.select().from(centralKitchenOrders).where(eq(centralKitchenOrders.id, orderId));
    if (!order) return [];
    const recipients = await routedRecipients(executor, order, event);
    return candidateUserIds.filter(id => recipients.includes(id));
  }
  // Unrecognized legacy rows cannot safely prove a current assignment.
  return [];
}

export async function canUserAccessCentralKitchenNotification(
  executor: DatabaseExecutor,
  notification: Pick<SystemNotification, "accessModule" | "accessBranchIds" | "targetUserIds"> & Partial<SystemNotification>,
  userId: string,
): Promise<boolean> {
  if (notification.accessModule !== "central_kitchen_orders") return true;
  const exactRecipients = notification.targetUserIds || [];
  if (!exactRecipients.includes(userId)) return false;
  const authorized = await filterAuthorizedCentralKitchenNotificationUsers(
    executor,
    notification,
    [userId],
  );
  return authorized.includes(userId);
}

export async function insertCentralKitchenNotification(
  tx: DatabaseExecutor,
  input: {
    eventId: number;
    orderId: number;
    event: CentralKitchenNotificationEvent;
    branchId: string;
    actorId: string;
  },
): Promise<number | null> {
  const [order] = await tx.select().from(centralKitchenOrders).where(eq(centralKitchenOrders.id, input.orderId));
  if (!order) throw new Error("Notification order not found");
  let escalationId: number | null = null;
  if (input.event === "created" && !(await getKitchenRouting(tx, order.centralKitchenId)).hasKitchenResponsible) {
    escalationId = await insertCentralKitchenNotification(tx, { ...input, event: "missing_responsible", branchId: order.centralKitchenId });
  }
  const recipients = await routedRecipients(tx, order, input.event);
  if (!recipients.length) return escalationId;
  const [created] = await tx.insert(systemNotifications).values(
    buildCentralKitchenNotificationPayload({ ...input, recipientIds: recipients }),
  ).onConflictDoNothing({ target: systemNotifications.dedupeKey })
    .returning({ id: systemNotifications.id });
  return created?.id || escalationId;
}

export async function routedRecipients(tx: DatabaseExecutor, order: any, event: CentralKitchenNotificationEvent): Promise<string[]> {
  const kitchen = await getKitchenRouting(tx, order.centralKitchenId);
  const kitchenIds = [kitchen.responsibleUserId, kitchen.deputyUserId].filter(Boolean) as string[];
  const ops = async () => (await routingPeople(tx)).filter((p: any) =>
    ["operations_manager", "production_development_manager"].includes(p.role) && routingPermission(p.role, p.actions || [], "view")).map((p: any) => p.id);
  if (event === "overdue" && ["received", "cancelled"].includes(order.status)) return [];
  if (["missing_responsible", "overdue"].includes(event)) return ops();
  if (["created", "edited", "cancelled", "received"].includes(event)) return kitchenIds;
  if (event === "received_discrepancy") return Array.from(new Set([...kitchenIds, ...await ops()]));
  const branchRouting = await getKitchenRouting(tx, order.requestBranchId);
  const people = await routingPeople(tx, order.requestBranchId);
  return people.filter((p: any) => routingPermission(p.role, p.actions || [], "view")
    && (p.id === order.createdBy || p.role === "branch_manager"
      || (["prepared", "dispatched"].includes(event) && p.id === branchRouting.receiverUserId)))
    .map((p: any) => p.id);
}

// Only open orders qualify. A stable per-order key survives scheduler restarts,
// retries and multiple server instances; creation/date edits do not spam ops.
export async function escalateOverdueKitchenOrders(db: any) {
  const orderingPolicy = await loadCentralKitchenOrderingPolicy(db);
  const ids = await db.transaction(async (tx: any) => {
    const orders = await tx.select().from(centralKitchenOrders).where(and(
      inArray(centralKitchenOrders.status, ["requested", "approved", "prepared", "dispatched"]),
      sql`(${centralKitchenOrders.neededDate}::date +
        (CASE WHEN ${centralKitchenOrders.neededTime} ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'
          THEN ${centralKitchenOrders.neededTime} ELSE ${orderingPolicy.defaultNeededTime} END)::time)
        < (now() AT TIME ZONE 'Asia/Riyadh')`,
    )).for("update", { skipLocked: true });
    const inserted: number[] = [];
    for (const order of orders) {
      const recipients = await routedRecipients(tx, order, "overdue");
      if (!recipients.length) continue;
      const [notification] = await tx.insert(systemNotifications).values({
        ...buildCentralKitchenNotificationPayload({ eventId: order.id, orderId: order.id, event: "overdue",
          branchId: order.centralKitchenId, actorId: order.createdBy, recipientIds: recipients }),
        dedupeKey: `central-kitchen-overdue:${order.id}:overdue`,
      }).onConflictDoNothing({ target: systemNotifications.dedupeKey }).returning({ id: systemNotifications.id });
      if (notification) inserted.push(notification.id);
    }
    return inserted;
  });
  for (const id of ids) dispatchCentralKitchenNotificationAfterCommit(id);
  return ids.length;
}

export function dispatchCentralKitchenNotificationAfterCommit(notificationId: number | null): void {
  if (!notificationId) return;
  void import("./db").then(async ({ db }) => {
    const [notification] = await db.select().from(systemNotifications)
      .where(eq(systemNotifications.id, notificationId)).limit(1);
    if (!notification) return;
    const { sendPushForSystemNotification } = await import("./push-service");
    await sendPushForSystemNotification(notification);
  }).catch((error) => {
    console.error("[central-kitchen-notification] post-commit push failed:", error?.message || error);
  });
}