import { and, eq, inArray, or } from "drizzle-orm";
import {
  systemNotifications,
  userBranchAccess,
  userPermissions,
  users,
  type SystemNotification,
} from "@shared/schema";

export type CentralKitchenNotificationEvent =
  | "created"
  | "edited"
  | "cancelled"
  | "approved"
  | "prepared"
  | "dispatched"
  | "received"
  | "received_discrepancy"
  | "discrepancy_resolved";

const EVENT_COPY: Record<CentralKitchenNotificationEvent, { title: string; content: string; priority: number }> = {
  created: { title: "طلب جديد للمطبخ المركزي", content: "وصل طلب فرع جديد ويحتاج إلى المراجعة.", priority: 3 },
  edited: { title: "تم تعديل طلب المطبخ المركزي", content: "عدّل الفرع الطالب بيانات طلب قائم.", priority: 2 },
  cancelled: { title: "تم إلغاء طلب المطبخ المركزي", content: "ألغى الفرع الطالب طلباً قائماً.", priority: 3 },
  approved: { title: "تم اعتماد طلب المطبخ المركزي", content: "اعتمد المطبخ المركزي الطلب.", priority: 2 },
  prepared: { title: "تم تجهيز طلب المطبخ المركزي", content: "أكمل المطبخ المركزي تجهيز الطلب.", priority: 2 },
  dispatched: { title: "تم إرسال طلب المطبخ المركزي", content: "خرج الطلب من المطبخ المركزي للتسليم.", priority: 3 },
  received: { title: "تم استلام طلب المطبخ المركزي", content: "أكد الفرع الطالب استلام الطلب.", priority: 2 },
  received_discrepancy: { title: "تم استلام الطلب مع فروقات", content: "سجّل الفرع الطالب فروقات عند استلام الطلب وتحتاج إلى المراجعة.", priority: 4 },
  discrepancy_resolved: { title: "تمت معالجة فروقات طلب المطبخ", content: "تم إغلاق فروقات الاستلام المسجلة على الطلب.", priority: 3 },
};

export function canReceiveCentralKitchenNotification(
  role: string,
  permissionActions: string[] | null,
): boolean {
  return role === "admin"
    || role === "operations_manager"
    || role === "branch_manager"
    || !!permissionActions?.includes("view");
}

export function buildCentralKitchenNotificationPayload(input: {
  eventId: number;
  orderId: number;
  event: CentralKitchenNotificationEvent;
  branchId: string;
  actorId: string;
  recipientIds: string[];
}) {
  const copy = EVENT_COPY[input.event];
  return {
    title: copy.title,
    content: copy.content,
    messageType: "central_kitchen_order",
    displayStyle: "banner",
    priority: copy.priority,
    targetAllBranches: false,
    targetBranchIds: [input.branchId],
    targetUserIds: input.recipientIds,
    buttonText: "فتح الطلب",
    buttonAction: `/central-kitchen-orders?orderId=${input.orderId}`,
    soundEnabled: true,
    // NotificationDisplay marks the row read as soon as it is rendered.
    // showOnce prevents the same lifecycle banner/sound replaying on reload,
    // while the normal read record remains available to notification history.
    showOnce: true,
    autoGenerated: true,
    autoSource: "central_kitchen_order",
    accessModule: "central_kitchen_orders",
    accessBranchIds: [input.branchId],
    dedupeKey: `central-kitchen-event:${input.eventId}`,
    createdBy: input.actorId,
  } as const;
}

type DatabaseExecutor = {
  select: (...args: any[]) => any;
  insert: (...args: any[]) => any;
};

export async function resolveCentralKitchenNotificationRecipients(
  executor: DatabaseExecutor,
  branchIds: string[],
  candidateUserIds?: string[],
): Promise<string[]> {
  if (!branchIds.length || candidateUserIds?.length === 0) return [];
  const branchUsers = executor.select({ userId: userBranchAccess.userId })
    .from(userBranchAccess)
    .where(inArray(userBranchAccess.branchId, branchIds));
  const rows = await executor.select({
    id: users.id,
    role: users.role,
    permissionActions: userPermissions.actions,
  }).from(users)
    .leftJoin(userPermissions, and(
      eq(userPermissions.userId, users.id),
      eq(userPermissions.module, "central_kitchen_orders"),
    ))
    .where(and(
      eq(users.isActive, "active"),
      or(
        eq(users.role, "admin"),
        eq(users.role, "operations_manager"),
        inArray(users.branchId, branchIds),
        inArray(users.id, branchUsers),
      ),
      ...(candidateUserIds ? [inArray(users.id, candidateUserIds)] : []),
    ));

  return Array.from(new Set(rows
    .filter((row: any) => canReceiveCentralKitchenNotification(
      row.role,
      Array.isArray(row.permissionActions) ? row.permissionActions : null,
    ))
    .map((row: any) => row.id)));
}

export async function filterAuthorizedCentralKitchenNotificationUsers(
  executor: DatabaseExecutor,
  notification: Pick<SystemNotification, "accessModule" | "accessBranchIds">,
  candidateUserIds: string[],
): Promise<string[]> {
  if (notification.accessModule !== "central_kitchen_orders") return candidateUserIds;
  return resolveCentralKitchenNotificationRecipients(
    executor,
    notification.accessBranchIds || [],
    candidateUserIds,
  );
}

export async function canUserAccessCentralKitchenNotification(
  executor: DatabaseExecutor,
  notification: Pick<SystemNotification, "accessModule" | "accessBranchIds" | "targetUserIds">,
  userId: string,
): Promise<boolean> {
  if (notification.accessModule !== "central_kitchen_orders") return true;
  const exactRecipients = notification.targetUserIds || [];
  if (!exactRecipients.includes(userId)) return false;
  const authorized = await filterAuthorizedCentralKitchenNotificationUsers(
    executor,
    notification,
    [userId],
  );
  return authorized.includes(userId);
}

export async function insertCentralKitchenNotification(
  tx: DatabaseExecutor,
  input: {
    eventId: number;
    orderId: number;
    event: CentralKitchenNotificationEvent;
    branchId: string;
    actorId: string;
  },
): Promise<number | null> {
  const recipients = await resolveCentralKitchenNotificationRecipients(tx, [input.branchId]);
  if (!recipients.length) return null;
  const [created] = await tx.insert(systemNotifications).values(
    buildCentralKitchenNotificationPayload({ ...input, recipientIds: recipients }),
  ).onConflictDoNothing({ target: systemNotifications.dedupeKey })
    .returning({ id: systemNotifications.id });
  return created?.id || null;
}

export function dispatchCentralKitchenNotificationAfterCommit(notificationId: number | null): void {
  if (!notificationId) return;
  void import("./db").then(async ({ db }) => {
    const [notification] = await db.select().from(systemNotifications)
      .where(eq(systemNotifications.id, notificationId)).limit(1);
    if (!notification) return;
    const { sendPushForSystemNotification } = await import("./push-service");
    await sendPushForSystemNotification(notification);
  }).catch((error) => {
    console.error("[central-kitchen-notification] post-commit push failed:", error?.message || error);
  });
}