import type { Request, Response } from "express";
import { eq } from "drizzle-orm";
import {
  advanceRequests, employeeEvaluations, jobOffers, leaveRequests, leaveSettlements,
  onboardingNotifications, systemNotifications, users, type SystemNotification,
} from "@shared/schema";
import type { SourceNotice } from "@shared/operations-center-notifications";
import { operationsAdvanceFinalAuthority } from "@shared/operations-center";
import { db, pool } from "./db";
import { sourceNoticeAccess, type SourceNoticeAccess } from "./source-notification-access";
import { peopleLeaveReviewer } from "./operations-people-predicates";
import { resolveReviewerJobTitle } from "./leave-helpers";

export type HrNoticeSource = "joining" | "leave" | "advance" | "leave_settlement" | "evaluation";
type Executor = Pick<typeof db, "select" | "insert">;
// Cache module loading only, never recipient grants or action decisions.
let authModule: Promise<typeof import("./auth")> | undefined;
const loadAuth = () => authModule ||= import("./auth");
export type HrNoticeContext = {
  source: HrNoticeSource; id: number; branchId: string; stage: string; module: string; href: string;
  title: string; currentLevel?: number; approvalChain?: unknown;
};

/** These keys describe persisted stages, not a guessed role or employee ID. */
export function hrNoticeIdentity(n: Partial<SystemNotification>): { source: HrNoticeSource; id: number; stage: string } | null {
  if (!n.autoGenerated || n.autoSource !== "hr_workflow" || !n.targetUserIds?.length) return null;
  const match = /^hr-workflow:(joining|leave|advance|leave_settlement|evaluation):([1-9]\d*):(signed|pending|pre_approved|level_[1-9]\d*|acknowledged)$/.exec(n.dedupeKey || "");
  if (!match || !Number.isSafeInteger(Number(match[2]))) return null;
  return { source: match[1] as HrNoticeSource, id: Number(match[2]), stage: match[3] };
}
export const isHrSourceNotification = (n: Partial<SystemNotification>) => n.autoSource === "hr_workflow";

async function context(source: HrNoticeSource, id: number, executor: Executor): Promise<HrNoticeContext | null> {
  let branchId: string | null = null, stage = "", module = "", path = "", parameter = "", title = "";
  let currentLevel: number | undefined, approvalChain: unknown;
  if (source === "joining") {
    const [n] = await executor.select().from(onboardingNotifications).where(eq(onboardingNotifications.id, id)).limit(1);
    if (!n || !n.branchId || n.status !== "signed" || !n.signedAt || n.confirmedAt || n.convertedAt
      || n.convertedEmployeeId || n.convertedBranchEmployeeId || n.cancelledAt) return null;
    const [offer] = await executor.select().from(jobOffers).where(eq(jobOffers.id, n.jobOfferId)).limit(1);
    if (!offer || offer.status !== "accepted" || offer.branchId !== n.branchId || offer.hiredEmployeeId) return null;
    branchId = n.branchId; stage = "signed"; module = "operations_joining";
    path = "/hr-hub"; parameter = "notificationId"; title = "مباشرة موقّعة تنتظر اعتماد التشغيل";
  } else if (source === "leave") {
    const [r] = await executor.select().from(leaveRequests).where(eq(leaveRequests.id, id)).limit(1);
    if (!r || r.status !== "pending" || !r.currentLevel) return null;
    branchId = r.branchId; currentLevel = r.currentLevel; approvalChain = r.approvalChain;
    stage = `level_${currentLevel}`; module = "hr_leaves"; path = "/hr/leaves"; parameter = "leaveId";
    title = "طلب إجازة ينتظر مراجعة المرحلة الحالية";
  } else if (source === "advance") {
    const [r] = await executor.select().from(advanceRequests).where(eq(advanceRequests.id, id)).limit(1);
    if (!r || !["pending", "pre_approved", "signed"].includes(r.status)) return null;
    branchId = r.branchId; stage = r.status; module = "hr_advances"; path = "/hr/advances"; parameter = "advanceId";
    title = stage === "signed" ? "سلفة موقّعة تنتظر الاعتماد النهائي" : "طلب سلفة ينتظر المراجعة المخولة";
  } else if (source === "leave_settlement") {
    const [r] = await executor.select().from(leaveSettlements).where(eq(leaveSettlements.id, id)).limit(1);
    if (!r || r.status !== "active" || !r.signedAt) return null;
    branchId = r.branchId; stage = "signed"; module = "hr_leaves"; path = "/hr/leaves"; parameter = "settlementId";
    title = "تصفية إجازة موقّعة تنتظر تأكيد الصرف";
  } else {
    const [r] = await executor.select().from(employeeEvaluations).where(eq(employeeEvaluations.id, id)).limit(1);
    if (!r || r.status !== "approved" || !r.employeeAckAt) return null;
    branchId = r.branchId; stage = "acknowledged"; module = "hr_evaluations"; path = "/hr/evaluations"; parameter = "evaluationId";
    title = "تم الإقرار بالاطلاع على تقييم الموظف";
  }
  if (!branchId) return null;
  const query = new URLSearchParams({ branchId, [parameter]: String(id),
    ...(source === "joining" ? { tab: "employees", section: "joining" } : {}) });
  // These legacy pages have no exact-record deep-link contract. Never invent
  // a CTA that opens an unrelated leave/evaluation. Their notices are factual.
  const href = source === "leave_settlement" || source === "evaluation" ? "" : `${path}?${query}`;
  return { source, id, branchId, stage, module, href, title, currentLevel, approvalChain };
}

/** Role shortcuts may not resurrect an explicit revocation of an action. */
async function actionAllowed(access: SourceNoticeAccess, module: string, action: string): Promise<boolean> {
  const { rowCount } = await pool.query(`SELECT 1 FROM user_permission_overrides o
    JOIN permissions p ON p.id=o.permission_id
    WHERE o.user_id=$1 AND p.module=$2 AND p.action=$3 AND o.allow=false
    AND (o.expires_at IS NULL OR o.expires_at>now())`, [access.user.id, module, action]);
  if (rowCount) return false;
  const { requirePermission } = await loadAuth();
  const req = { currentUser: access.user, method: "GET", headers: {},
    originalUrl: "/api/hr-source-notification" } as unknown as Request;
  return new Promise<boolean>((resolve, reject) => {
    const res = { status: () => res, json: () => resolve(false) } as unknown as Response;
    Promise.resolve(requirePermission(module, action)(req, res, err => err ? reject(err) : resolve(true))).catch(reject);
  });
}

export async function hrRecipientEligible(c: HrNoticeContext, access: SourceNoticeAccess): Promise<boolean> {
  if (!access.branch(c.branchId) || !await access.view(c.module)) return false;
  if (c.source === "joining") return access.user.role === "operations_manager"
    && !["main_warehouse", "hq", "head_office"].includes(c.branchId.toLowerCase())
    && Array.isArray(access.allowed) && access.allowed.includes(c.branchId)
    && await access.view("operations_hr") && await actionAllowed(access, c.module, "approve");
  if (c.source === "leave") {
    if (!await actionAllowed(access, c.module, "approve")) return false;
    return peopleLeaveReviewer(c.currentLevel!, c.approvalChain, {
      id: access.user.id, role: access.user.role, allowed: access.allowed,
      reviewerTitle: await resolveReviewerJobTitle(access.user.id),
    }).matches;
  }
  if (c.source === "advance") {
    const { HR_SPECIALIST_PERMISSIONS } = await loadAuth();
    const final = operationsAdvanceFinalAuthority(access.user.role, (HR_SPECIALIST_PERMISSIONS.hr_advances || []).includes("edit"));
    if (c.stage !== "pending" && !final) return false;
    return await actionAllowed(access, c.module, "approve") || await actionAllowed(access, c.module, "edit");
  }
  return actionAllowed(access, c.module, "edit");
}

/** Source mutations call this inside their transaction. Dedupe is per actual
 * persisted stage, and a missing reviewer is explicit rather than a broadcast. */
export async function queueHrSourceNotification(source: HrNoticeSource, id: number, executor: Executor = db): Promise<number | null> {
  if (!Number.isSafeInteger(id) || id < 1) throw new Error("Invalid HR notification source ID");
  const c = await context(source, id, executor);
  if (!c) return null;
  const candidates = await executor.select({ id: users.id }).from(users).where(eq(users.isActive, "active"));
  const recipients: string[] = [];
  // Keep transaction latency bounded without overwhelming the connection pool.
  for (let offset = 0; offset < candidates.length; offset += 6) {
    const batch = candidates.slice(offset, offset + 6);
    const eligible = await Promise.all(batch.map(async candidate => {
      const access = await sourceNoticeAccess(candidate.id);
      return !!access && await hrRecipientEligible(c, access);
    }));
    batch.forEach((candidate, index) => { if (eligible[index]) recipients.push(candidate.id); });
  }
  if (!recipients.length) {
    console.warn(`[hr-source-notification] No currently authorized recipient: ${source}:${id}:${c.stage}`);
    return null;
  }
  const [created] = await executor.insert(systemNotifications).values({
    title: c.title, content: "حدث مسجل في المصدر؛ راجع الحالة الحالية والصلاحية قبل تنفيذ أي إجراء.",
    messageType: "info", displayStyle: "toast", priority: 1, targetAllBranches: false,
    targetBranchIds: [c.branchId], targetUserIds: recipients, accessBranchIds: [c.branchId],
    accessModule: c.module, autoGenerated: true, autoSource: "hr_workflow",
    dedupeKey: `hr-workflow:${source}:${id}:${c.stage}`, buttonText: c.href ? "عرض السجل في المصدر" : null, buttonAction: c.href || null,
    showOnce: false,
  }).onConflictDoNothing({ target: systemNotifications.dedupeKey }).returning({ id: systemNotifications.id });
  return created?.id ?? null;
}

/** READ/PUSH integration MUST use this gate. Stored IDs are not grants; a
 * changed stage, revoked authority or vanished source removes the notice. */
export async function projectHrSourceNotificationForRecipient(n: SystemNotification, userId: string): Promise<SourceNotice | null> {
  const key = hrNoticeIdentity(n);
  if (!key || !n.targetUserIds?.includes(userId)) return null;
  const c = await context(key.source, key.id, db);
  if (!c || c.stage !== key.stage || n.accessModule !== c.module
    || n.accessBranchIds?.length !== 1 || n.accessBranchIds[0] !== c.branchId) return null;
  const access = await sourceNoticeAccess(userId);
  if (!access || !await hrRecipientEligible(c, access)) return null;
  return { ...n, sourceState: "current", title: c.title,
    content: "حدث مسجل في المصدر؛ راجع الحالة الحالية والصلاحية قبل تنفيذ أي إجراء.",
    targetAllBranches: false, targetBranchIds: [c.branchId], accessBranchIds: [c.branchId],
    buttonAction: c.href || null, buttonText: c.href ? "عرض السجل في المصدر" : null };
}