import { and, desc, eq, gte, isNull, lte, or, sql } from "drizzle-orm";
import { db } from "./db";
import {
  wasteRiskRules,
  wasteRiskAlerts,
  wasteReports,
  wasteItems,
  cashierSalesJournals,
  comparisonSummaries,
  systemNotifications,
  type WasteRiskRule,
} from "@shared/schema";

// Threshold types supported by the governance engine. All stored as free text in
// waste_risk_rules.threshold_type, so adding a new type needs NO DB migration.
export const WASTE_RULE_TYPES = {
  daily_waste_percent: "نسبة الهدر اليومي للفرع",
  repeat_days: "تكرار هدر الصنف (عدد الأيام)",
  shortage: "فجوة العجز غير المبرر",
  approval_gate: "بوابة موافقة المدير",
} as const;

export type WasteRuleType = keyof typeof WASTE_RULE_TYPES;

function addDays(dateStr: string, delta: number): string {
  const d = new Date(`${dateStr}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + delta);
  return d.toISOString().split("T")[0];
}

async function getDailyWastePercent(branchId: string, date: string): Promise<{ percent: number; wasteValue: number; sales: number }> {
  const reports = await db
    .select({ totalValue: wasteReports.totalValue })
    .from(wasteReports)
    .where(and(eq(wasteReports.branchId, branchId), eq(wasteReports.reportDate, date)));
  const wasteValue = reports.reduce((s, r) => s + (Number(r.totalValue) || 0), 0);

  const salesRow = await db
    .select({ totalSales: sql<number>`coalesce(sum(total_sales), 0)::numeric` })
    .from(cashierSalesJournals)
    .where(and(eq(cashierSalesJournals.branchId, branchId), eq(cashierSalesJournals.journalDate, date)));
  const sales = Number(salesRow[0]?.totalSales || 0);

  const percent = sales > 0 ? (wasteValue / sales) * 100 : 0;
  return { percent, wasteValue, sales };
}

// Returns true if an open alert already exists for this rule/branch/date (and product),
// so we never spam duplicate alerts for the same condition on the same day.
async function findOpenAlert(ruleId: number, branchId: string, alertDate: string, productName: string | null) {
  const conditions = [
    eq(wasteRiskAlerts.ruleId, ruleId),
    eq(wasteRiskAlerts.branchId, branchId),
    eq(wasteRiskAlerts.alertDate, alertDate),
    eq(wasteRiskAlerts.status, "open"),
    productName ? eq(wasteRiskAlerts.productName, productName) : isNull(wasteRiskAlerts.productName),
  ];
  const [existing] = await db.select().from(wasteRiskAlerts).where(and(...conditions)).limit(1);
  return existing;
}

async function createBranchNotification(params: {
  branchId: string;
  title: string;
  content: string;
  severity: string;
}) {
  try {
    await db.insert(systemNotifications).values({
      title: params.title,
      content: params.content,
      messageType: "warning",
      displayStyle: "toast",
      priority: params.severity === "critical" ? 5 : params.severity === "high" ? 4 : 3,
      isActive: true,
      targetAllBranches: false,
      targetBranchIds: [params.branchId],
      autoGenerated: true,
      autoSource: "waste_governance",
      soundEnabled: params.severity === "critical",
    });
  } catch (err) {
    console.error("[waste-governance] failed to create notification:", err);
  }
}

async function upsertAlert(params: {
  rule: WasteRiskRule;
  branchId: string;
  alertDate: string;
  productName: string | null;
  category: string | null;
  currentValue: number;
  notifyTitle: string;
  notifyContent: string;
}) {
  const { rule, branchId, alertDate, productName, category, currentValue } = params;
  const existing = await findOpenAlert(rule.id, branchId, alertDate, productName);
  if (existing) {
    // Refresh the current value so the alert reflects the latest reading.
    await db
      .update(wasteRiskAlerts)
      .set({ currentValue })
      .where(eq(wasteRiskAlerts.id, existing.id));
    return { created: false };
  }
  await db.insert(wasteRiskAlerts).values({
    ruleId: rule.id,
    branchId,
    alertDate,
    productName,
    category,
    currentValue,
    thresholdValue: rule.thresholdValue,
    severity: rule.severity || "medium",
    status: "open",
  });
  await createBranchNotification({
    branchId,
    title: params.notifyTitle,
    content: params.notifyContent,
    severity: rule.severity || "medium",
  });
  return { created: true };
}

async function evaluateDailyWastePercent(rule: WasteRiskRule, branchId: string, date: string) {
  const { percent } = await getDailyWastePercent(branchId, date);
  if (percent > rule.thresholdValue) {
    await upsertAlert({
      rule,
      branchId,
      alertDate: date,
      productName: null,
      category: rule.category || null,
      currentValue: Math.round(percent * 100) / 100,
      notifyTitle: "⚠️ تجاوز نسبة الهدر اليومي",
      notifyContent: `نسبة الهدر اليوم بلغت ${percent.toFixed(1)}% وتجاوزت الحد المسموح (${rule.thresholdValue}%). يرجى المراجعة.`,
    });
  }
}

async function evaluateRepeatDays(rule: WasteRiskRule, branchId: string, date: string) {
  const windowDays = Math.max(1, rule.periodDays || 7);
  const startDate = addDays(date, -(windowDays - 1));

  // Count the number of DISTINCT days each product appeared in waste within the window.
  const rows = await db
    .select({
      productId: wasteItems.productId,
      days: sql<number>`count(distinct ${wasteReports.reportDate})`,
      totalQty: sql<number>`coalesce(sum(${wasteItems.quantity}), 0)`,
    })
    .from(wasteItems)
    .innerJoin(wasteReports, eq(wasteItems.wasteReportId, wasteReports.id))
    .where(
      and(
        eq(wasteReports.branchId, branchId),
        gte(wasteReports.reportDate, startDate),
        lte(wasteReports.reportDate, date),
      ),
    )
    .groupBy(wasteItems.productId);

  for (const row of rows) {
    const days = Number(row.days || 0);
    if (days >= rule.thresholdValue) {
      await upsertAlert({
        rule,
        branchId,
        alertDate: date,
        productName: String(row.productId),
        category: rule.category || null,
        currentValue: days,
        notifyTitle: "🔁 صنف متكرر الهدر",
        notifyContent: `صنف (#${row.productId}) تكرر هدره خلال ${days} أيام من آخر ${windowDays} يوم. يرجى مراجعة كميات الإنتاج.`,
      });
    }
  }
}

async function evaluateShortage(rule: WasteRiskRule, branchId: string, date: string) {
  const windowDays = Math.max(1, rule.periodDays || 7);
  const startDate = addDays(date, -(windowDays - 1));

  // Use the most recent comparison summary whose period overlaps the window.
  const [summary] = await db
    .select()
    .from(comparisonSummaries)
    .where(
      and(
        eq(comparisonSummaries.branchId, branchId),
        gte(comparisonSummaries.periodEnd, startDate),
        lte(comparisonSummaries.periodStart, date),
      ),
    )
    .orderBy(desc(comparisonSummaries.periodEnd))
    .limit(1);

  if (!summary) return;
  const shortage = Number(summary.totalShortage || 0);
  if (shortage > rule.thresholdValue) {
    await upsertAlert({
      rule,
      branchId,
      alertDate: date,
      productName: null,
      category: rule.category || null,
      currentValue: shortage,
      notifyTitle: "❗ فجوة عجز غير مبرر",
      notifyContent: `تم رصد عجز غير مبرر قدره ${shortage} وحدة (منتَج أكثر من المباع + الهالك). يرجى التدقيق.`,
    });
  }
}

// Main entry: evaluate all active rules for a branch on a given date.
export async function evaluateWasteGovernance(params: { branchId: string; date: string }): Promise<void> {
  const { branchId, date } = params;
  if (!branchId || !date) return;
  try {
    const orScope = or(eq(wasteRiskRules.branchId, branchId), isNull(wasteRiskRules.branchId));
    const rules = await db
      .select()
      .from(wasteRiskRules)
      .where(and(eq(wasteRiskRules.isActive, true), orScope!));

    for (const rule of rules) {
      try {
        switch (rule.thresholdType as WasteRuleType) {
          case "daily_waste_percent":
            await evaluateDailyWastePercent(rule, branchId, date);
            break;
          case "repeat_days":
            await evaluateRepeatDays(rule, branchId, date);
            break;
          case "shortage":
            await evaluateShortage(rule, branchId, date);
            break;
          // approval_gate is enforced at approval time, not via alerts.
          default:
            break;
        }
      } catch (ruleErr) {
        console.error(`[waste-governance] rule ${rule.id} failed:`, ruleErr);
      }
    }
  } catch (err) {
    console.error("[waste-governance] evaluation failed:", err);
  }
}

// Checks whether an approval gate is configured and currently exceeded for a branch/date.
// Returns required=true when a high-waste report must carry a manager justification.
export async function checkApprovalGate(params: { branchId: string; date: string }): Promise<{
  required: boolean;
  threshold: number | null;
  currentPercent: number;
}> {
  const { branchId, date } = params;
  const orScope = or(eq(wasteRiskRules.branchId, branchId), isNull(wasteRiskRules.branchId));
  const gates = await db
    .select()
    .from(wasteRiskRules)
    .where(and(eq(wasteRiskRules.isActive, true), eq(wasteRiskRules.thresholdType, "approval_gate"), orScope!));

  if (gates.length === 0) return { required: false, threshold: null, currentPercent: 0 };

  // Precedence: a branch-specific gate overrides global gates. Among the chosen
  // scope, apply the STRICTEST (lowest threshold) so policy is never under-enforced.
  const branchSpecific = gates.filter((g) => g.branchId === branchId);
  const candidates = branchSpecific.length > 0 ? branchSpecific : gates;
  const gate = candidates.reduce((min, g) => (g.thresholdValue < min.thresholdValue ? g : min), candidates[0]);

  const { percent } = await getDailyWastePercent(branchId, date);
  return {
    required: percent > gate.thresholdValue,
    threshold: gate.thresholdValue,
    currentPercent: Math.round(percent * 100) / 100,
  };
}
