// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/floor-plan-redesign/CommandBarWorkspace.tsx": () => import("../components/mockups/floor-plan-redesign/CommandBarWorkspace.tsx"),
  "./components/mockups/floor-plan-redesign/CompactInspector.tsx": () => import("../components/mockups/floor-plan-redesign/CompactInspector.tsx"),
  "./components/mockups/floor-plan-redesign/TouchWorkspace.tsx": () => import("../components/mockups/floor-plan-redesign/TouchWorkspace.tsx")
};
