// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/branch-workspace/Current.tsx": () => import("../components/mockups/branch-workspace/Current.tsx"),
  "./components/mockups/branch-workspace/Mobile.tsx": () => import("../components/mockups/branch-workspace/Mobile.tsx"),
  "./components/mockups/branch-workspace/Workspace.tsx": () => import("../components/mockups/branch-workspace/Workspace.tsx"),
  "./components/mockups/floor-plan-redesign/CommandBarWorkspace.tsx": () => import("../components/mockups/floor-plan-redesign/CommandBarWorkspace.tsx"),
  "./components/mockups/floor-plan-redesign/CompactInspector.tsx": () => import("../components/mockups/floor-plan-redesign/CompactInspector.tsx"),
  "./components/mockups/floor-plan-redesign/TouchWorkspace.tsx": () => import("../components/mockups/floor-plan-redesign/TouchWorkspace.tsx"),
  "./components/mockups/hr-hub-redesign/CommandCenter.tsx": () => import("../components/mockups/hr-hub-redesign/CommandCenter.tsx"),
  "./components/mockups/hr-hub-redesign/SmartSections.tsx": () => import("../components/mockups/hr-hub-redesign/SmartSections.tsx"),
  "./components/mockups/hr-hub-redesign/WorkflowTabs.tsx": () => import("../components/mockups/hr-hub-redesign/WorkflowTabs.tsx"),
  "./components/mockups/kitchen-orders/Current.tsx": () => import("../components/mockups/kitchen-orders/Current.tsx"),
  "./components/mockups/kitchen-orders/Streamlined.tsx": () => import("../components/mockups/kitchen-orders/Streamlined.tsx")
};
