import type { SystemNotification } from "./schema";

export type SourceNotice = SystemNotification & { sourceState?: "current" | "history" };

/** Recognition is not authorization. Only server-authored, exact source rows
 * may be projected after the live source/recipient gate has passed. */
export function recognizedSourceNotice(n: Partial<SystemNotification>): "kitchen" | "transfer" | "delivery" | null {
  if (!n.autoGenerated || !n.targetUserIds?.length) return null;
  if (n.autoSource === "warehouse_material_transfer" && n.accessModule === "warehouse"
    && /^warehouse-transfer:[1-9]\d*:[a-z_]+:/.test(n.dedupeKey || "")) return "transfer";
  if (n.autoSource === "central_kitchen_order" && n.accessModule === "central_kitchen_orders"
    && /^central-kitchen-(event|overdue):[1-9]\d*(?::[a-z_]+)?$/.test(n.dedupeKey || "")) return "kitchen";
  if (n.autoSource === "delivery_task" && n.accessModule === "delivery_tasks"
    && /^delivery:[1-9]\d*:.+/.test(n.dedupeKey || "")) return "delivery";
  return null;
}

/** The canonical recipient/workflow eligibility is checked by storage first.
 * This second gate prevents a notice scoped outside the selected view from leaking into it. */
export function noticeInSelectedScope(
  notice: Pick<SystemNotification, "targetAllBranches" | "targetBranchIds" | "accessBranchIds">,
  selected: string[],
): { kind: "general" | "branch"; branchIds: string[] } | null {
  const scope = notice.accessBranchIds?.length ? notice.accessBranchIds
    : notice.targetAllBranches ? null : notice.targetBranchIds;
  if (!scope) return notice.targetAllBranches
    ? { kind: "general", branchIds: [] } : null;
  // A notice covering an unselected (or ungranted) branch may contain details
  // about that branch in its freeform text. Never partially expose it.
  if (!scope.length || !scope.every(id => selected.includes(id))) return null;
  return { kind: "branch", branchIds: Array.from(new Set(scope)) };
}

export function publicCenterNotice(
  n: SourceNotice,
  scope: NonNullable<ReturnType<typeof noticeInSelectedScope>>,
  read: boolean,
) {
  return {
    id: n.id, title: n.title, content: n.content, messageType: n.messageType,
    priority: n.priority, createdAt: n.createdAt, buttonText: n.buttonText,
    buttonAction: n.buttonAction, kind: scope.kind, branchIds: scope.branchIds, read,
    ...(n.sourceState ? { sourceState: n.sourceState } : {}),
  };
}

export function parseNoticeAction(action: string | null | undefined, origin: string): string | null {
  if (!action || !action.startsWith("/") || action.startsWith("//") || /[\\\u0000-\u001f\u007f]/.test(action)) return null;
  try {
    const url = new URL(action, origin);
    if (url.origin !== origin || !url.pathname.startsWith("/") || url.pathname.startsWith("//")) return null;
    return `${url.pathname}${url.search}${url.hash}`;
  } catch { return null; }
}